### ISSUE TITLE
RequestEntityTooLarge error when people list is too long

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#102]
MS has 28kb limit for message size. 
Link: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels
![image](https://user-images.githubusercontent.com/37203901/133884027-4d648ab0-92df-4972-9234-ddb1c9bbd039.png)

**Comment by jimmidier** [comment]
- [ ] make every list card initially show at most 10 people, then provide a way to show more

**Comment by AttackOnMorty** [comment]
Related issues:
- [ ] [1. Type "Who works in Melbourne?"](#25)
- [ ] [2. Type "Who knows Azure?"](#14)
- [ ] [3. Type "I need to talk to a DevOps expert in Melbourne"](#15)
- [ ] [9. Type "Who is working on SugarLearning?"](#17)
- [ ] [10. Type "Who is on client work?"](#18)
- [ ] [11. Type "Who is free next Friday?"](#19)
- [ ] [12. Type "Who is on client work next Friday?"](#21)
- [ ] [13. Type "Who is free next Friday in Melbourne with Angular skills?"](#73 ) 
Will have the issue since the response will be changed to a list card.
- [ ] [14. Type "Who is working for SSW Today?"](#22)
- [ ] [15. Type "Who is in the Sydney office right now?"](#23)

**Comment by AttackOnMorty** [comment]
- [ ] For the list card, change from 15 per page to 10 per page and use "next 10..." instead of headings for subsequent pages.

**Comment by AttackOnMorty** [comment]
> * [ ]  For the list card, change from 15 per page to 10 per page and use "next 10..." instead of headings for subsequent pages.

Move this to #110
