### ISSUE TITLE
Roadmap - The yellow brick road for SophieBot

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#118]
Items before the v1 release:

- [ ] Get feature complete (aka Milestone v1.0.0)
- [ ] Review the feedback of last years Chewing the Fat feedback (with Adam and Piers)
- [ ] 📈 App Insights - Measure the usage
- [ ] Send Patrick a Test Please (inc Github repo)
- [ ] Send Piers a Test Please (inc Github repo)
- [ ] Send Calum a Test Please (inc Github repo)
- [ ] Send Uly a Test Please (inc Github repo)
- [ ] Send Adam a Test Please (inc Github repo)
- [ ] 📈 App Insights - Measure the usage
- [ ] Make a SSW TV video v1
- [ ] Launch it - Chewing the Fat (to 50 people)
- [ ] 📈 App Insights - Measure the usage
- [ ] Make fixes from their feedback (SSW users)
- [ ] Make an SSW TV video v2
- [ ] Release it
- [ ] Make fixes from their feedback (the public)
—
- [ ] Improve the People API

**Comment by AttackOnMorty** [comment]
Move roadmap to the [Wiki](https://github.com/SSWConsulting/SSW.SophieBot/wiki)
