### ISSUE TITLE
⭐ Query - When is John Smith's next availability 

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#185]
Cc: @theixdev @AttackOnMorty 

  
### Pain

People want to know when is someone available

### Tasks (only do the easy ones)

- [x] When is John Smith's next availability
- [x] When is John next available
- [x] When will John next be free 
- [x] When is John next Free/Available
- [x] When will John finish his current booking
- [x] When is John's next bookable

### Hard Tasks
- [x] When is John next free for 3 days?  
Feedback from @theixdev

Thanks!

**Comment by jimmidier** [comment]
- [ ] Have a test for all queries

**Comment by jimmidier** [comment]
Easy ones are implemented.

![image](https://user-images.githubusercontent.com/16027480/151363610-60024293-85c0-41e3-8a5b-6502ec96652f.png)
**Figure: Command responses from the "easy ones"**

**Comment by ravidhaduk** [comment]
As per conversation with Adam during Sprint Review, Add this new feature to the SophieBot Try out page.
- [ ] Add it.

**Comment by ravidhaduk** [comment]
Done - Added to the SophieBot Try page
><img width="854" alt="image" src="https://user-images.githubusercontent.com/80997507/158279100-1cb12904-d382-4754-ba8b-d7c495c8f705.png">
Figure: Added new query "When is Piers next free for 2 days?" to the [Try Out Page](https://sswsophie.com/try/)
