### ISSUE TITLE
Query - When is Calum free

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#204]
Cc: @brydeno@JeanThirion @AttackOnMorty 

  
### Pain

Feeback from @brydeno and @JeanThirion 
> When is Adam next bookable? 
> When is XXX next free"

People want to know when will someone be free

### Suggested Solution

We need to support querying someone's free time. e.g.
Q: When is Calum free?
A: Calum will be free on 13/12/2021. (Also add "View Bookings", "More Booking Info" and "View Profile Card" buttons)

### Tasks

- [x] Query 
  - "When is Jim next free"
  - "When is Jim's next bookable"
  - "When is Bryden available?"

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/138996424-422b31d8-6b32-42ba-86a8-515db03cb296.png)
**Figure: Wrong answer**

Thanks!

**Comment by AttackOnMorty** [comment]
- [ ] Change text from `Calum Simpson​​ will free at Sat 1 Jan 2022.` to `Calum Simpson​​ will be free on Sat 1 Jan 2022.`
- [ ] Add two buttons `More Booking Info` and `View Profile`

**Comment by jimmidier** [comment]
- [ ] Support: "When is Calum's next bookable?"

**Comment by AttackOnMorty** [comment]
- [ ] Change text
From
Piers Sinclair will be free on Today.
To
Piers Sinclair is free Today.
- [ ] Change all "View Calendar" icons to CRM icons

![image](https://user-images.githubusercontent.com/37203901/142959927-63ccf91c-92cb-499e-ba4d-9ac79a9b02dd.png)
**Figure: Grammer mistake and icon is not correct**

**Comment by jimmidier** [comment]
- [ ] Support "When is Jim next free"
- [ ] Support "When is Jim's next bookable"
