### ISSUE TITLE
✨ Query - Show calendar for Brendan

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#224]
Cc: @jernejk @AttackOnMorty 

  
### Pain

From @jernejk's feedback,
> What is Jason's agenda?

We need to support asking someone's agenda.
Related to [https://github.com/SSWConsulting/SSW.SophieBot/issues/139#issuecomment-952501546](https://github.com/SSWConsulting/SSW.SophieBot/issues/139#issuecomment-952501546)

### Tasks

- [x] Query -
  - "What is Jason's agenda?"
  - "Show Jason's Bookings"
  - "What's Jean's next booking?"

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/140092350-457a8b17-c6e5-48fb-8108-1810297855aa.png)
**Figure: Refer to response from the old bot**

Thanks!

**Comment by AttackOnMorty** [comment]
- [ ] Change card title to Patrick Zhao’s next appointments [10]
- [ ] Add icon before the name and button
- [ ] Change “Details in CRM” to “More Booking Info”

**Comment by jimmidier** [comment]
- [ ] auto-name correction
- [ ] name duplication strategy

**Comment by AttackOnMorty** [comment]
- [ ] Data is not correct. Calum doesn't have any appointments on Sunday.

![image](https://user-images.githubusercontent.com/37203901/142554586-0bff68a5-e77d-41f1-94c5-720d9a41ff3d.png)
**Figure: Calendar shows Calum have an appointment on Sunday**

![image](https://user-images.githubusercontent.com/37203901/142554602-40a0c934-f728-46f5-83b1-964054ae7931.png)
**Figure: PeopleAPI data source**

**Comment by AttackOnMorty** [comment]
- [ ] TBD: Current calendar shows the first appointment of the day. One person might have multiple appointments in a day. Should it show all the appointments?

![image](https://user-images.githubusercontent.com/37203901/142559809-6cf27d27-da85-4c95-a176-edf0a11c334f.png)
**Figure: Bot response**

**Comment by jimmidier** [comment]
> * [x]  Data is not correct. Calum doesn't have any appointments on Sunday.
> 
> ![image](https://user-images.githubusercontent.com/37203901/142554586-0bff68a5-e77d-41f1-94c5-720d9a41ff3d.png) **Figure: Calendar shows Calum have an appointment on Sunday**
> 
> ![image](https://user-images.githubusercontent.com/37203901/142554602-40a0c934-f728-46f5-83b1-964054ae7931.png) **Figure: PeopleAPI data source**

![image](https://user-images.githubusercontent.com/16027480/142807634-76ed3499-2c67-4120-bd85-c604c15845f3.png)
**Figure: Fixed by https://github.com/SSWConsulting/SSW.SophieBot/pull/290**

**Comment by jimmidier** [comment]
- [ ] Query -
  - "What is Jason's agenda?"
