### ISSUE TITLE
♻️ Telemetry - Track usages on buttons

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#271]
Cc: @AttackOnMorty @adamcogan @pierssinclairssw 

  
### Pain

As per conversation with @adamcogan, we need telemetry for button usages

### Tasks

Track clicks on 
- [ ] "More"/"Less" on profile card
- [ ] "View in People"/"View in CRM"/"View Calendar"
- [ ] other possible buttons

Thanks!

**Comment by jimmidier** [comment]
> Track clicks on
> 
> 1. "More"/"Less" on profile card
> 2. "View in People"/"View in CRM"/"View Calendar"
> 3. Other possible buttons

    > "More"/"Less" on profile card
Unsupported in adaptive card
    > "View in People"/"View in CRM"/"View Calendar"
Only "View Calendar" is supported
    > Other possible buttons
Only intent redirecting buttons are supported for telemetry, "View Calendar" above as an example
