### ISSUE TITLE
✨ Query - Which client is Calum working for?

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#304]
Cc: @JeanThirion @AttackOnMorty 

  
### Pain

From @JeanThirion's feedback,
> "Who is XXX booked for" 

We need to support querying clients

### Tasks

- [x] Query - 
  - "Which client is Calum working for?"
  - "Who is Calum booked for?"
  - "Who is Calum working for?"

Thanks!

**Comment by ravidhaduk** [comment]
Done - Client query implemented.

Not adding any screenshots as all the information is confidential. 

I will demo it during the Review meeting.

**Comment by ravidhaduk** [comment]
As per the conversation during Sprint Review, We have to set an example of client card with Bob-Northwind client data to add this new feature in the SophieBot Try Out page. And add new button in the client card called "View colleagues" after implementing this issue #484. 

- [ ] Add Bob-Northwind client data.
- [ ] Add this feature to the SophieBot Try Out Page.
- [ ] Add "View colleagues" button in the card.

**Comment by ravidhaduk** [comment]
Now external user can test this query.

<img width="907" alt="Screen Shot 2022-03-30 at 5 38 14 pm" src="https://user-images.githubusercontent.com/80997507/160767437-91cad26c-0b22-49ed-aa5d-7a0ee8d49691.png">
Figure: Bob Northwind client card from the SophieBot.
