### ISSUE TITLE
✨Implement the following queries relating to a client

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.SophieBot#316]
cc @adamcogan, @AttackOnMorty, @pierssinclairssw @brydeno
Hi @jimmidier,

As per the screenshot below, I tried to query about the client “Northwind” but the bot couldn’t find any results.

- [ ] Please investigate 
- [ ] I would like the following questions/queries to work
  - Tell me about Northwind?
  - Tell me about the client Northwind?
  - Tell me about the project Northwind?
  - Who works on Northwind?

![image](https://user-images.githubusercontent.com/57518417/142817014-3dfb1d21-981e-48b5-9b4d-5947544d32b7.png)
**Figure: chatlog with SophieBot in relation to the client Northwind**

**Comment by brydeno** [comment]
Jim, 
I wouldn't think of this as a bug. The requirements you were implementing were fulfilled. Jack has just suggested some new features.

**Comment by jimmidier** [comment]
> Jim, I wouldn't think of this as a bug. The requirements you were implementing were fulfilled. Jack has just suggested some new features.

Hi @brydeno 

Thanks for the note. Jack has suggested some new features in the sample queries list, but I've also received bugs from the screenshot he posted

**Comment by jimmidier** [comment]
cc @AttackOnMorty 

As per the comments above, 

### Tasks
- [ ] Please investigate 
- [ ] I would like the following questions/queries to work
  - Tell me about Northwind?
  - Tell me about the client Northwind?
  - Tell me about the project Northwind?
  - Who works on Northwind?
  - Who will be working for Campion?
- [ ] Improve LUIS model to improve the answers for the four queries in the screenshot above
  - tell me about [the (client | project)]Northwind
  - who works on Northwind
