### ISSUE TITLE
✨ Support for not available (annual leave/sick leave/training days/etc)

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.SophieBot#328]
Hi team,
  
### Pain

Right now, I believe being on leave means the person is free which is not correct.

We should be able to know if a person is "free" (internal work),  on client work or not available (sick/annual/etc leave).
There is also SSW booking so that probably should be considered.

### Suggested Solution

Suggested queries:
- Is Patrick free today?
  - No, Patrick is not at work today.
- Is JK available next week?
  - JK is available on Monday.
  - He also works for a client on Tuesday and Wednesday.
  - And is not available on Thursday and Friday.
- Is Kaha on leave?
  - Yes, Kaha is on leave.

### Tasks

- [ ] Asses the viability of the feature
- [ ] Update existing queries to support leave
- [ ] Add "Is X on [sick/annual/training] leave?", "Who is not working today?"

Thanks!
