### ISSUE TITLE
✨ Add Client Booking Summary over a date range

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.SophieBot#330]
Cc: @jimmidier 

Hi,
  
### Pain
I want to see who is booked on a specific client over the next x weeks - either for my use, or the clients

### Suggested Solution
Input the question 'Who is booked on [client] in the next [x] [weeks]'

And get back a table

### Tasks

- [ ] Define question in LUIS
- [ ] Fetch data from CRM
- [ ] Present in a table

### Screenshots

Similar to this:
![image](https://user-images.githubusercontent.com/10430890/142982553-fb8b09ae-a9cd-4eec-abf3-bc8e2a31c899.png)

Thanks!
