### ISSUE TITLE
♻️ UI - Who is Adam Cogan

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#332]
Cc: @pierssinclairssw @adamcogan  

Hi @AttackOnMorty 

### Pain

As per conversation with @pierssinclairssw  and @adamcogan, we need to do UI updates on profile card.

### Tasks

- [x] ~~Change button text from:
    View Calendar 
    To: 
    View Bookings~~ (Done in #334 )
- [x] ~~Use nick names as a fallback strategy in GetProfileAction. Please action this update in People API.~~ (Done in https://dev.azure.com/ssw/SSW.SophieBot/_workitems/edit/65657)
- [ ] Update labels (e.g. Today, Last Seen) and chat icon color to red
- [ ] Change the "V" in more button in profile card to a more solid one
- [ ] Change "View in People" icon to four squares SSW icon. 
Refer to https://www.ssw.com.au/ssw/include/pigeon/img/favicon-32x32.png

### Screenshots
![image](https://user-images.githubusercontent.com/37203901/143516095-7f1ab276-20dd-4433-9ab6-71bb157bcdd5.png)
**Figure: Current profile card**

Thanks!
