### ISSUE TITLE
♻️ Hook into Crm data sync function to update LUIS list entity at runtime

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#342]
Cc: @AttackOnMorty 

Related to #295 #320 #338 
Resolves #117 (task `list entity runtime training`)

### Pain

LUIS prebuilt person name entity is currently unable to recognize certain person names, causing failed response on queries such as "Who is JK" and "Show me Ulys skills".
Fixing the list entity with missing person names one by one manually is not a robust solution, as the missed names list could go on and on. 

### What code could be improved?

We need a way to periodically syncronize business data to LUIS, as well as train and publish LUIS application at runtime.

### Tasks

- [ ] Update People API to provide complete people names within our organization
- [ ] Update SophieBot to have a service for runtime LUIS training and publishment
- [ ] Hook into Crm data sync function app to do model syncronization on each data sync

### More Information

See [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/developer-reference-resource](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/developer-reference-resource) for more information about REST API and SDK for LUIS.

Thanks!
