### ISSUE TITLE
✨ Integrate Where do you want to go today

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#350]
Cc: @kikibianc @AttackOnMorty @adamcogan 

  
### Pain

Request from @kikibianc:

> As per our chat, I am giving this task to the SophieBot team. In the past, Patrick tested QnaMaker with our "Where do you want to go today" page at https://sswcom.sharepoint.com/SitePages/where-do-you-want-to-go-today.aspx and it worked nicely.
> With SophieBot on a new framework now, I believe this task can be revisited to add that page to our SophieBot.
> Questions like:
> 1.	Where is the intranet?
> 2.	Where is CRM?
> 3.	How to see reports?
> 
> Should be answered based on that page

SSW has a nice "Where do you want to go today" page acting as a navigation entry for the intranet. As per request from @kikibianc and @adamcogan, we need to integrate the data on that page into SophieBot queries.

### Suggested Solution

- Create Qna service for static content like this

### Tasks

- [x] Investigate on the data source
- [x] Create Qna service
- [x] Implement dialogs for asking about intranet, e.g.
  - Where is the intranet?
  - Where is CRM?
  - How to see reports?

### More Information

See "Where do you want to go today" page at [https://sswcom.sharepoint.com/SitePages/where-do-you-want-to-go-today.aspx](https://sswcom.sharepoint.com/SitePages/where-do-you-want-to-go-today.aspx)

Thanks!

**Comment by ravidhaduk** [comment]
Done -  Implemented QnA service to access "Intranet | Where do you want to go today?" in the SophieBot

><img width="924" alt="Screen Shot 2022-03-14 at 3 19 41 pm" src="https://user-images.githubusercontent.com/80997507/158107127-ea89703b-49a2-40a8-aa8c-ef19b977b98a.png">
><img width="929" alt="Screen Shot 2022-03-14 at 3 19 28 pm" src="https://user-images.githubusercontent.com/80997507/158107171-bfbe6622-6c9d-4199-85f5-2c9a2b3c1c46.png">
><img width="926" alt="Screen Shot 2022-03-14 at 3 19 06 pm" src="https://user-images.githubusercontent.com/80997507/158107180-960bfbc1-fc74-4f9e-bbd6-879a0d04f977.png">
><img width="941" alt="Screen Shot 2022-03-14 at 3 19 16 pm" src="https://user-images.githubusercontent.com/80997507/158107186-288afb99-bab9-4d58-9557-1db8709bbabf.png">
><img width="954" alt="Screen Shot 2022-03-14 at 3 18 53 pm" src="https://user-images.githubusercontent.com/80997507/158107196-df3af981-9fbd-49f9-a736-ccb9d6a6f31e.png">
>Figure: Exmples of response from the SophieBot regarding "Where do you want to go today?"

**Comment by ravidhaduk** [comment]
Done -  Implemented QnA service to access "Intranet | Where do you want to go today?" in the SophieBot

><img width="924" alt="Screen Shot 2022-03-14 at 3 19 41 pm" src="https://user-images.githubusercontent.com/80997507/158107127-ea89703b-49a2-40a8-aa8c-ef19b977b98a.png">
><img width="929" alt="Screen Shot 2022-03-14 at 3 19 28 pm" src="https://user-images.githubusercontent.com/80997507/158107171-bfbe6622-6c9d-4199-85f5-2c9a2b3c1c46.png">
><img width="926" alt="Screen Shot 2022-03-14 at 3 19 06 pm" src="https://user-images.githubusercontent.com/80997507/158107180-960bfbc1-fc74-4f9e-bbd6-879a0d04f977.png">
><img width="941" alt="Screen Shot 2022-03-14 at 3 19 16 pm" src="https://user-images.githubusercontent.com/80997507/158107186-288afb99-bab9-4d58-9557-1db8709bbabf.png">
>Figure: Examples of response from the SophieBot regarding "Where do you want to go today?"

**Comment by ravidhaduk** [comment]
As per the feedback from Adam, System Admins and other teams members, there are some changes in this query in order to make responses consistent and hide sensitive information. 
- [ ] Make all links to the actual URL in the response of "Where is the SSW DevOps?". 
>![image](https://user-images.githubusercontent.com/80997507/159598486-05607701-a1e4-448b-9690-2cb862c24e06.png)
Figure: SophieBot Response when you ask "Where is SSW DevOps?".

- [ ] Hide password manager information.
- [ ] Hide UNC.

**Comment by ravidhaduk** [comment]
As per the conversation during Sprint Review, we have to investigate how we can manage confidential information such as Google Accounts, Password Manager name and UNC's.
- [ ] Investigate.

**Comment by ravidhaduk** [comment]
As per the conversation, the source should be clickable to the "[Where do you want to go?](https://sswcom.sharepoint.com/SitePages/where-do-you-want-to-go-today.aspx)" SharePoint Page for each response of the QnA. 
![123tempsnip](https://user-images.githubusercontent.com/80997507/164588485-286e9a2b-1477-4b8d-abe0-1ba7c79ebb30.png)
Figure: Make this source clickable.

- [ ] Action.

**Comment by ravidhaduk** [comment]
As per the conversation with Adam and Jean, we need to dynamically get QnA content from SharePoint instead of adding them through the .tsv file. 
- [ ] Investigate how you can achieve the result.
- [ ] Implement it.

**Comment by ravidhaduk** [comment]
Done – It is no longer hardcoded. SophieBot works with QnA Maker and automatically refreshes content from SharePoint now using Power Automate flows.
