### ISSUE TITLE
🐛  Skill query doesn't support fuzzy matching

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#353]
Cc: @tiagov8 @jimmidier 

To myself

### Describe the Bug

Skill query uses exact match. Take skill "Dynamics 365 - CRM" as an example, so you can't search with "Dynamics" or "CRM". You have to search with the full name.

### Tasks
- [x] Fix query - "who knows Dynamics 365 - CRM" first
- [x] Use fuzzy matching for skills to support queries like "who knows dynamics" and "who knows crm"

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/144157260-cb520edc-5db4-4c56-a1a3-8d690911c2eb.png)
**Figure: Bot can't understand full skill name**

![image](https://user-images.githubusercontent.com/37203901/144157364-3289788f-844a-48d8-9b1a-13ae2d666b7a.png)
**Figure: Skill doesn't support fuzzy matching**

Thanks!

**Comment by AttackOnMorty** [comment]
- [ ] Fix the error below
![image](https://user-images.githubusercontent.com/37203901/144774221-cb06ca2f-e7c8-45f4-9c43-daaa947ecc5c.png)
**Figure: Get an error after selecting a location**
