### ISSUE TITLE
♻️ Test - Impersonating external users

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#361]
Cc: @AttackOnMorty @pierssinclairssw @adamcogan 

### Pain

Since we are now performing authentication for bot users, we need a way to do a proper testing.

### What code could be improved?

Impersonating external users in Teams

### Tasks

- [x] Investigate on getting an organization account outside SSW
- [x] Create a test purpose Microsoft 365 tenant
- [x] Create a test user in the tenant above
- [x] Test SophieBot with the user above, see if secret information is hidden from external access

Thanks!

**Comment by jimmidier** [comment]
Tested pass from @chrisschultzssw
