### ISSUE TITLE
♻️ Change label colors and icon colors to accent

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#366]
Cc: @AttackOnMorty @pierssinclairssw @adamcogan 

### Pain

The red colors we are using on certain labels and icons are not having a consistent looking. 

### What code could be improved?

As per conversation with @pierssinclairssw and @adamcogan , we need to change them to purple/blue ("Accent" in adaptive card codes)

### Tasks

- [x] Change labels and chat icon to be in "Accent" style
- [x] Change chat icon to "Chat in Teams" button
- [x] Change labels in Availability card to be in "Accent" style
- [x] Use a 👤 in "View Profile Card" button on "When is Adam free" response card

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/145135464-1fe9863e-68e8-4a3e-b288-66f08b9758ed.png)
**Figure: Profile card with red labels and icon**

Thanks!
