### ISSUE TITLE
✨ Query - Who's been using SophieBot

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#371]
Cc: @pierssinclairssw @adamcogan @AttackOnMorty 

  
### Pain

We don't have a direct way to show every user the bot usage data.

### Tasks

- [x] Add an Intent for query "Who's been using SophieBot"
- [x] Default to show top 10 within last month
- [ ] ~Add buttons to show more~
- [x] Show link to App Insights analytics
- [x] After it's implemented, add it to the official [try out page](https://sswsophie.com/try/)

Thanks!

**Comment by jimmidier** [comment]
- [ ] Investigate on passing the time interval i.e. 30days to Azure Workbook

**Comment by jimmidier** [comment]
- [ ] Fix the time zone issue which causes incorrect data
