### ISSUE TITLE
✨  External user access - Show all buttons and use "show" link for sensitive infos

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#378]
Cc: @jimmidier @PatrickZhao1989 @adamcogan @pierssinclairssw 

Hi @jimmidier 
  
### Pain

Currently,  we are hiding buttons (e.g. View in CRM) and sensitive information (e.g. client) for external users. But we didn't mention it on our official SophieBot website (https://sswsophie.com/try/) , which is not user-friendly.

### Suggested Solution

- For buttons, we will keep them for external users. After clicking it, we will show messages like "You are not connected to the CRM system. Please contact SSWSophieBotDevs@ssw.com.au to set it up."
- For sensitive information, we will use "show" link instead of displaying "xxx". After clicking it, we will show messages like "Sorry, you are an external user and you can't see this info. You can subscribe to our paid tier to see your own data"

### Tasks

- [x] Keep buttons for external users instead of hiding them
- [x] Use "show" link for sensitive information
    - Use "Show >" and "< Hide"
- [ ] Update try page at [https://sswsophie.com/try/](https://sswsophie.com/try/)

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/146501299-6fbcddf8-299f-4a4c-9c57-25de58fd268e.png)
**Figure: "View in People" and "View in CRM" buttons will be hidden from external users**

![image](https://user-images.githubusercontent.com/37203901/146498664-c17e7f70-244a-40c1-a3e9-e2fb541317aa.png)
**Figure: Sensitive client info blured out**

Thanks!
