### ISSUE TITLE
✨ Add Customer Subscription Feature

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#381]
Cc: @PatrickZhao1989 @pierssinclairssw @adamcogan 

Hi @jimmidier and @DavidAbraham082 
  
### Pain

As per our conversation, we need to add an enterprise customer subscription form on https://sswsophie.com/sophiebot/, providing a free trial to build their own SophieBot.

### Tasks

To @DavidAbraham082 
- [ ] On the page above, please add a pricing overview with two pricing tiers: Free Trial and Paid
- [ ] When the user choose the pricing, provide a form for the user to fill in their company name, email address
- [ ] Once the customer signed up, make a request to the bot endpoint to do user sign up
 
To @jimmidier 
- [ ] Create an endpoint to sign up user
- [ ] Create the tenant identity and seed the dummy data
- [ ] Provision the tenant and all the dummy data through the email
- [ ] Create an endpoint for WordPress to retrieve information of the user, including tenant-related data
- [ ] Send email to the customer after successful signup
- [ ] Confirm with Adam at which point should we charge the subscriber, and what are the actual differences between the pricing tiers

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/146512619-0a0a0ce5-2795-4998-bbbf-3c74adf843fd.png)
**Figure: Pricing will be added above the Bots Development/Consulting section**

Thanks!

**Comment by jimmidier** [comment]
Closing as we're not going to implement multitenancy
