### ISSUE TITLE
✨ Usability testing from zero to “who is in the Sydney office”

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#383]
Cc: @DavidAbraham082 @PatrickZhao1989 @pierssinclairssw @adamcogan 

Hi @jimmidier 
  
### Pain

We need to perform usability testing to make sure external users can set up and run our project from scratch.

### Tasks

- [ ] Setup an external user account
- [ ] Setup and run the project
- [ ] Test the bot

Thanks!
