### ISSUE TITLE
✨ PowerApps solution POC

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#406]
Cc: @adamcogan @DavidAbraham082 @pierssinclairssw 

  
### Pain

As per @adamcogan's requirement, we need a data mapping solution for Dynamics365 systems to talk to our People API.

### Suggested Solution
Do a POC of PowerApps Solution

### Tasks

- [x] Get a demo with sample data that customers can try
- [x] Create a PowerApps solution
- [x] Have it talk to the PeopleAPI

Thanks!

**Comment by jimmidier** [comment]
Common solution:

**Prerequisite**: The customer has a particular CRM system, say Dynamics365
**Step 1**: SSW - Provide an exported PowerApps solution in the source code
![image](https://user-images.githubusercontent.com/16027480/148503526-e86ddee6-7e0c-4981-ab3d-27a96ca33db4.png)
**_Figure: PowerApps solution with table schema definitions and other components, acting as a connector between customer's CRM and People API_**

**Step 2**: Customer - imports our packaged solution to their PowerApps
**Step 3**: Customer - choose a proper data connector and configure data mappings
![image](https://user-images.githubusercontent.com/16027480/148504170-0b9ff244-dc83-4b44-ba96-f22529dc44e4.png)
**_Figure: There are many data connectors provided by Power Platform that the customer can choose from_**

**Step 4**: Customer - do data seeding with the configurations set from above. Now all data is ready for People API to consume.
**Step 5**: Customer - configure the People API they purchased to query the data sources built from above.
**Step 6**: Customer - Try out SophieBot with their own data

Note:
- We can provide tech support at any step above
- This PowerApps solution is feasible for a wide range of data source, though not all of them
- If this solution doesn't suit the customer's needs, they can either implement by their own or choose our tech support
- We can iterate the solution to support more business models e.g. support push model apart from the pull model above
