### ISSUE TITLE
✨ Query - "Who was in the office last week?" v1

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#410]
Cc: @landonmaxwell

Hi @DavidAbraham082 
  
### Pain

From @landonmaxwell,

> We would like to be able to use SophieHub to keep track of who has been in the office to mitigate COVID risks. 
> 1.	Add questions to SophieHub to allow us to see who is in the office on a specific date.
> •	Date specific, e.g. Who was in the office 24/12/21?
> •	Date ranges, e.g. Who was in the office between 24/12/21 – 4/01/2022?
> •	Relative terms, e.g. Who was in the office last Friday?
> •	Compound searches, e.g. Who was in the office last week?
> ![image](https://user-images.githubusercontent.com/16027480/148716824-3f3f8934-1b66-4b99-b607-266a834b52fd.png)
> **Figure: We would like SophieBot to be able to give info on who was in the office on a specific date, like when you search “Who is in the office right now?”.**

### Tasks

- [x] Investigate whether we can get location tracking data from UniFi
- [x] If yes, update People API to support location history query
- [x] If not, implement location tracking in People API
- [x] Implement the command

### More Information

UniFi SDK at [https://github.com/schwoi/UnifiClient](https://github.com/schwoi/UnifiClient)

Thanks!

**Comment by jimmidier** [comment]
- [ ] Fix the time zone issue which causes incorrect data
