### ISSUE TITLE
✨ Query - "Who was in the office last week?" v2

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#425]
Cc: @adamcogan @pierssinclairssw @ravidhaduk

Undone work from https://github.com/SSWConsulting/SSW.SophieBot/issues/410
  
### Pain

As per conversation during the sprint review, we need some UI changes

### Tasks

- [x] For query "Who is in Sydney right now", indicate the 1-hour time range: Change the date text
    From:
        Wednesday 19 January
    To:
        Wed 19 Jan 10am-11am
- [x] For query "Who is in Sydney today", indicate the all-day time range: Change the date text
    From:
        Wednesday 19 January
    To:
        Wed 19 Jan All day
- [x] For query "Who was in Sydney on Jan 18", indicate time span: Change the date text
    From:
        Friday 14 January
    To:
        Friday 14 January (3 days ago)
- [x] Use spaces for all "xxx-xxx" format text
- [x] Abbreviate all date texts e.g. From Monday to Mon, January to Jan
- [ ] Add related new queries to [try page](https://sswsophie.com/try/)

Thanks!

**Comment by jimmidier** [comment]
![image](https://user-images.githubusercontent.com/16027480/150950334-83cad8fb-9bd6-4872-9bb2-fe9ee59e184a.png)
**Figure: Different kinds of datetime/datetime range texts**
