### ISSUE TITLE
🐛 Failed to process action button on "Who works in Newcastle" response card

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#428]
Cc: @adamcogan @pierssinclairssw @ravidhaduk @DavidAbraham082 

### Describe the Bug

As per conversation during sprint review, the "(x in the office today)" action button on the "Who works in Newcastle" response card is not working.

This is a missing point when the LUIS entity usage and the query string for the PeopleAPI call was changed in https://github.com/SSWConsulting/SSW.SophieBot/issues/410.

### To Reproduce
1. Go to SophieBot conversation on Teams
2. Send a message "Who works in Newcastle"
3. Click the "(x in the office today)" action button on the response card
4. See the failure prompt "Please specify a valid date to query."

### Expected Behavior

Clicking "(x in the office today)" will give the same response as asking "Who is working in Newcastle today"

### Tasks
- [ ] Query string fix - Update query string usage at https://github.com/SSWConsulting/SSW.SophieBot/blob/main/bots/employee-finder/src/SSW.SophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog#L54
- [ ] LUIS usage fix - Update entity parameters at https://github.com/SSWConsulting/SSW.SophieBot/blob/main/bots/employee-finder/src/SSW.SophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg#L79
- [ ] Ensure related codes anywhere else are all fixed accordingly

### Environment
 - Device: PC
 - OS: Windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/150086819-7fc7d52a-03a4-41af-ab26-0c6fc782befb.png)
**FIgure: Clicking "0 in the office today" gets a failure response**

Thanks!

**Comment by jimmidier** [comment]
Fixed by updating the intent redirection code to have corresponding entities passed in.

![image](https://user-images.githubusercontent.com/16027480/150905585-fcd13d82-7dea-4e6a-9fc6-1496134cc3cf.png)
**Figure: Text link now works fine**

**Comment by DavidAbraham082** [comment]
<3
