### ISSUE TITLE
♻️ Fetch timesheet data for last 90 days instead of last 30 days

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#445]
Cc: @adamcogan @pierssinclairssw @ravidhaduk 

### Pain

As per conversation, we decided to get timesheet data for last 90 days to have a better overview

### What code could be improved?

Timesheet synchronization app needs to be updated

### Tasks

- [x] Action the update

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
![image](https://user-images.githubusercontent.com/16027480/150957597-04f0add2-f737-457b-98d3-06169160c6aa.png)
**Figure: Project related queries now fetch data for last 90 days**
