### ISSUE TITLE
♻️ Improve date text for Query "Who is in Sydney right now/today"

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#458]
Cc: @adamcogan @ravidhaduk 

Hi @ravidhaduk 

### Pain

As per our conversation during the sprint review, we want to make the date text more helpful

### What code could be improved?

![image](https://user-images.githubusercontent.com/16027480/151514608-c217315e-9931-4f79-9921-ebc748522584.png)
**Figure: Prepend a "(today)" hint after the date for all similar cards**

### Tasks

- [ ] Implement the changes

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
