### ISSUE TITLE
🐛 MAC matching problem on iOS

### ISSUE THREAD

**Issue by leahy268** [SSWConsulting/SSW.SophieBot#460]
Cc: @pierssinclairssw, @bradystroud 

Hi,

### Describe the Bug

We have an issue with using the MAC address which has come up.  

On IOS 14 and above, by default they have private MAC address turned on.  This causes a different mac address to be used each time the device connects to the WIFI. This will stop Sophiebot from knowing who is in the office if they have an iPhone.

I have investigated if we can only allow devices to connect with this turned off but the feature is not available at this stage from Ubiquiti.  

However it appears that we can use the Ubiquiti API to get the users instead.  See https://community.ui.com/questions/UniFi-API-browser-tool-updates-and-discussion/30927150-dd44-40f7-96c0-9fbbfc673fb3 

This would provide a more reliable method of seeing who was connected to Kiwi as it would support Apple devices and wouldn't require a manual entry in CRM.
### Tasks
1. Investigate if the API gets the information that we require.
2. Implement that as the method for working out who is in the office.

### Environment
 Any iPhone or iPad running IOS 14 or later

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Done - Fixed in https://dev.azure.com/ssw/SSW.SophieBot/_git/SSW.SophieBot/pullrequest/4380:
Added integration with UniFi list users endpoint to also consider user name matching when querying on-site employees
