### ISSUE TITLE
♻️ Update "days" text in people on client or internal work card.

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#463]
Cc:

Hi @ravidhaduk 

### Pain

As per my conversation with Adam, change
From: 
         Note: Free for 0 day over next 4 weeks.
To:
         Note: Free for 0 days over the next 4 weeks.

### What code could be improved?

https://github.com/SSWConsulting/SSW.SophieBot/blob/75cb09eedc08ee8ca4060670bc9b3726f4ccb886/bots/employee-finder/src/SSW.SophieBot/language-generation/en-us/common.en-us.lg#L116

### Tasks

- [x] Refactor code here.

### Screenshots

<img width="605" alt="Screen Shot 2022-02-15 at 3 50 35 pm" src="https://user-images.githubusercontent.com/80997507/153994828-392a8f62-02bd-42df-834e-c478bda894a4.png">
Figure: Where there is 0 days. 

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
