### ISSUE TITLE
♻️ Update SophieBot name

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#464]
Cc:

Hi @ravidhaduk 

### Pain

As per conversation with Adam, SophieBot name should be updated 
From:
         SSWSophieBot
To:
         SSW SophieBot

### Tasks

- [x] Update the name.

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
<img width="283" alt="Screen Shot 2022-02-28 at 10 08 32 am" src="https://user-images.githubusercontent.com/80997507/155903936-630555e6-cd96-4347-a47c-257eff04fd51.png">
Figure: Updated SophieBot name.
