### ISSUE TITLE
🐛 Fix the data for "Who is free today" query

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#465]
Cc:

Hi

### Describe the Bug

SophieBot gives incorrect data when you ask "Who is free today". 

### Tasks
- [x] Investigate the date source
- [x] Fix the error.

### Screenshots

<img width="248" alt="image" src="https://user-images.githubusercontent.com/80997507/153998261-3ad8695f-4163-4b09-9087-795569dc600e.png">
Figure: SophieBot response of Internal work

![image](https://user-images.githubusercontent.com/80997507/153998324-a7c5d83c-7556-4521-81d5-f15fd8102b61.png)
Figure: CRM booked days.

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
As per the investigation,  PostBulkUpdateAppoitments function is failing since 27 Jan 2022. The reason it is failing is that there is a property size limit exceeds when it try to store the date. That property could be appointments as per my investigation.

**Comment by ravidhaduk** [comment]
Done by storing appointments in a seperate table.
![image](https://user-images.githubusercontent.com/80997507/157807060-22420293-3f6b-4501-84af-e984cdc4e591.png)
![image](https://user-images.githubusercontent.com/80997507/157807068-34b68144-7f79-4a2e-b68f-ed8d9ca9ed30.png)
