### ISSUE TITLE
♻️View Projects when 0

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#470]
Cc: @ravidhaduk @jimmidier @adamcogan 

### Pain

As per the email from Adam, Change the text of the "View Projects" button with the number of projects because it should not be a surprise when the user has zero projects.

Change "View Projects" button text
       From
                "View Projects"
       To
                "View Projects (5)" - When 5 projects
                OR 
              "View Projects (none)" - When zero projects

### Screenshots

<img width="974" alt="image" src="https://user-images.githubusercontent.com/80997507/156947178-2b932d7c-f7c1-48d1-a853-9782120e5b83.png">
Figure: When use has Zero projects.

### Tasks

- [ ] Update the "View Projects" button text with the number of Projects.

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done - Updated View Projects button text with the number of projects.


<img width="1000" alt="Screen Shot 2022-03-08 at 3 35 15 pm" src="https://user-images.githubusercontent.com/80997507/157167169-6731f3b6-f38d-409b-8077-8796d2411b73.png">
Figure: View Projects button When use has a number of projects.
