### ISSUE TITLE
♻️ Add e2e testing and set up alerts on server monitor

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#472]
Cc: @adamcogan @ravidhaduk 

### Pain
We have experienced bugs, UI flaws and even server downtime that were not discovered until SophieBot went live. 
- Automated testing is needed to ensure all commands are working well on production.
- Server monitor needs to be properly set to notify the team about critical problems

### What code could be improved?
We can add e2e testing to our SophieBot web app to detect critical problem during dev/prod deployment.

### Tasks

- [ ] Add e2e testing to web app 
    - [ ] (Recommended) Use Playwright
- [ ] Integrate e2e testing into dev/prod GitHub Actions
- [ ] Set up email/Teams notification on Application Insights

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
