### ISSUE TITLE
♻️View Projects UX

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#474]
Cc: @jimmidier 

Hi @ravidhaduk 

### Pain

As per the conversation during Sprint Review with @adamcogan, We have to make some changes to the View Projects card.  

<img width="569" alt="Screen Shot 2022-03-14 at 9 34 22 am" src="https://user-images.githubusercontent.com/80997507/158082291-0d7951e0-3979-4195-9c23-21c189a01185.png">
Figure: Current View Projects card.

### Tasks

- [x] Move client name to the first column. 
- [x] Narrow down the "Worked" column. 
- [x] Remove Project Id column from the card.
- [x] Underline the Project name as this field is clickable. 
- [ ] Filter the projects of employees in the "View in CRM" button at the bottom of the card. 

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
In Progress - View Projects card has been updated as per the requirements except for the last one. 

>![image](https://user-images.githubusercontent.com/80997507/158107793-1cef8256-96ed-47f5-93d3-a093e5fe6178.png)
>Figure: Updated View Projects card in the SophieBot.

**Comment by ravidhaduk** [comment]
We can't filter projects in the CRM because we are using the TimePro data source to filter projects in the SophieBot. 
Another solution to this problem is to make client names clickable and link them to the CRM.

**Comment by ravidhaduk** [comment]
As per the conversation with Ulysses and Jean, there are some suggestions regarding this problem,

Suggestions are as follows:

- Add the CRM logo next to the project name to make it configurable.
- Change button text from “View in CRM” to “View all Projects [1000X]”.
- Add a second button “View in PowerBI” which will link to the PowerBI’s Employee Review page.

We are waiting for Adam's feedback and approval to implement this.

**Comment by ravidhaduk** [comment]
As per our conversation during Sprint Review, closing this issue without further changes.
