### ISSUE TITLE
♻️ View Employee Responsibilities needs a count

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#477]
Cc: @adamcogan @jimmidier 

Hi @ravidhaduk 

### Pain

As per the email from Adam, Employee Responsibilities button need a counts indicating number of responsibilities. Since employees responsibilities are stored in the SharePoint, You need to contact SharePoint expert regarding how you will get the data.

Change from:
‘View in Employee Responsibilites’
To
‘View Employee Responsibilites (22)’

### Tasks

- [ ] Add counts in View Employee Responsibilities.

### Screenshots

<img width="667" alt="image" src="https://user-images.githubusercontent.com/80997507/159601782-5b10129b-8670-4212-9a68-14ed896329cd.png">
Figure: Profile card from the SophieBot.

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
