### ISSUE TITLE
♻️ Who is on client work - Add authentication to prevent external access

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#481]
Cc: @pierssinclairssw @adamcogan 

Hi @ravidhaduk 

### Pain

As per our conversation, the response for query "Who is on client work" has a Clients column to list client names, which is confidential.

### What code could be improved?

Authentication against external users should be implemented on this query.

### Tasks

- [ ] Add authentication for this command to prevent external users from getting the entire response

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/160337231-4d503c53-5489-4a05-a514-484fe7f9588b.png)
**Figure: The main content on the response is client names**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Duplicate of https://github.com/SSWConsulting/SSW.SophieBot/issues/485#issuecomment-1086974688. Closing
