### ISSUE TITLE
♻️Who is Calum | Today field - Make client name a link to show client profile

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#482]
Cc: @pierssinclairssw @adamcogan 

Hi @ravidhaduk 

### Pain

We now have a command to get client profile, and we've observed that "Who is Adam Cogan" is the most popular command currently, thus we would like to add a link from the employee profile to the client profile.

### What code could be improved?

The client name field on the Today field, if there's any.

### Tasks

- [ ] Update client name on the "Today" field to be a link to the specific client profile, same as the response from command "Which client is Calum working for"

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/160338125-9d10c8e2-3512-47fe-90c5-cc8deff41ed5.png)
**Figure: Please update the blurred client name to be a link**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
