### ISSUE TITLE
✨ Investigate and implement a way of seeing colleagues

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#484]
Cc: @pierssinclairssw @adamcogan

Hi  @ravidhaduk 
  
### Pain

As per our conversation, we would like a way to see people someone talked to recently.

### Tasks

- [ ] Investigate
- [ ] Create tasks
- [ ] Implement

### More Information

There's a Graph API doc for reference https://docs.microsoft.com/en-us/graph/api/user-list-people

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
