### ISSUE TITLE
♻️ Add authentication for "Who is on client work" query.

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#485]
Cc: @ravidhaduk @jimmidier @pierssinclairssw @adamcogan 

Hi 

### Pain

As per the conversation during Sprint Review, we want to hide all the information of "who is on client work?" from external users. Currently, if external user ask this query, sophieBot will reply with below added card with hidden client name. It is unreasonable to show this card. 

### Tasks

- [x] Add authentication in this query.
- [x] Remove Show/Hide button and directly display the client name.

### Screenshots

<img width="924" alt="Screen Shot 2022-03-29 at 1 17 17 pm" src="https://user-images.githubusercontent.com/80997507/160519328-b756717d-8104-45c9-9768-eded4fed193c.png">
Figure: Hide this card from external users.

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
As per the conversation during Sprint Review, we want previous functionality back to mitigate potential of sharing confidential information.
- [ ] Add it back.

**Comment by ravidhaduk** [comment]
Done.
<img width="772" alt="Screen Shot 2022-04-08 at 4 13 59 pm" src="https://user-images.githubusercontent.com/80997507/162375506-b02a8407-e669-49e7-a766-fe2cb907eef5.png">
Figure: Put Show/Hide functionality back.
