### ISSUE TITLE
🐛 Bug - Billed column is not showing the correct data

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.SophieBot#488]
Cc: @jimmidier @adamcogan 
Hi @ravidhaduk 

### Describe the Bug
On SophieBot, when I ask who is in Sydney, the billed last 90 days field appears incorrect. For example, Adam is showing as 105 days billed in the last 90 days.

### To Reproduce
Ask "Who is in Sydney"

### Expected Behavior
Billed reflects the number of days billed in the last 90 days.

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - OS: Windows 11

### Screenshots
![image](https://user-images.githubusercontent.com/79821522/161455797-a8b70ed9-3e91-43bc-931b-08a9e0f8f4da.png)
**Figure: Adam has 105 days billed in the last 90 days, which is impossible**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by duanxinhuan** [comment]
As per my conversation with Ravi, Penny and Adam, the curent billed column is showing both internal work and client work, but we only want it to show the actual 'billed hours' which is the client work hours.

To reflect this change, change people API to filter out the internal working hours. 

- [ ] Investigate.
- [ ] Action.
