### ISSUE TITLE
♻️   Migrate from .net core 3.1 to .net 6

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#490]
Cc: @adamcogan @ravidhaduk @jimmidier 

Hi 

### Pain

Currently, the People API is using .NET Core Version 3.1 and Azure Functions Version 3.1. Which is not compatible with macOS with an M1 chip base. So, upgrading these version will help M1 Mac users to run this project on their machine.

Ms Doc:
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

### What code could be improved?

Upgrade the version to .net 6 + Azure function 4.1 because it will support M1 chip

### Tasks

- [x] Upgrate the version from .net core 3.1 + Azure function 3.1 to .net 6 + Azure function 4.1

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
