### ISSUE TITLE
👷Unify workflow files for different environment using templates

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#496]
Cc: @matt-goldman @ravidhaduk @adamcogan 

  
### Pain

The GitHub action files for dev and prod environment have much duplicated thus need a way to unify into one and make it multistage.

### Suggested Solution

Use [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)

### Tasks

- [ ] Create composite actions
- [ ] Unify workflow files
- [ ] Make multistage

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
