### ISSUE TITLE
👷Use binary artifacts for prod deployment

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#497]
Cc: @wicksipedia @ravidhaduk @adamcogan 

  
### Pain

During runs of GitHub Actions, codes are compiled twice when deploying to prod.

### Suggested Solution

Upload artifacts and use them for prod deployment
⛔Do this after #496 

### Tasks

- [ ] Use artifacts for prod deployment jobs

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
