### ISSUE TITLE
🐛 Limit result set for all "Show All" actions

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#500]
Cc: @ravidhaduk

### Describe the Bug

We're experiencing strange behavior on Teams that, some employee lists are rendered twice with a single request. As per testing this bug only happens when the result list is too long (possibly when exceeding 30 items).

### To Reproduce
1. Go to MS Teams (web app or desktop app)
2. Ask SophieBot "Who knows Angular"
3. On the summary card returned, click "Show All [33]"
4. See the overall list is rendered twice

### Expected Behavior

The overall list is rendered once, which shows exactly the number of items from the "Show All" text

### Tasks
- [ ] Investigate whether it's related to business code within the bot or PeopleAPI (less likely as explained in next section)
- [ ] Investigate whether it's related to rate-limiting in Teams or an issue in Teams itself (more likely as explained in next section)
- [ ] If it's business code related, fix it
- [ ] If it's related to rate-limiting in Teams, investigate a way to remove it
- [ ] If it's an issue in Teams itself or it's due to rate limit and cannot be addressed, change all "Show All" buttons to show only top ones
    - Ask the PO for approval first
    - The top amount can be around 30
    - Report the Teams issue to Microsoft if appropriate

### More Information

Judging from the F12 networking results above, it's more likely to be an issue in Teams, that one of the call to Teams server returned status 502.

![image](https://user-images.githubusercontent.com/16027480/170814441-e747db44-c873-412c-8888-bc2078120b93.png)
**❌Failed Example: "Who knows Angular?" | "Show All [33]"**

![image](https://user-images.githubusercontent.com/16027480/170814444-f98c9079-4249-4064-a363-58eeb0d915e1.png)
**❌Failed Example: "Who is free today?" | "Show All [52]" (asked on Saturday)**

![image](https://user-images.githubusercontent.com/16027480/170814354-19a99b9c-d865-4ca0-92b3-7e73ba558b44.png)
**✅Successful Example: "Who is on client work next Monday?" | "Show All [27]"**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by duanxinhuan** [comment]
Hi @jimmidier @ravidhaduk 

I Just research into this issue, I I find an existing Github Issues [5668](https://github.com/MicrosoftDocs/msteams-docs/issues/5668)

I checked the rate limit firstly and find out that it seems not go over the rate limit.
Then I tried to click button several times, I found out that any request that last less than 15 seconds do not send me the duplicated result.
Finally I dive into the action code, it seems like we don't manage a long-run operation as it is supposed to be.

Can we refer to ms doc:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0
and see if the problem still exist?

Thanks,
Jack

**Comment by jimmidier** [comment]
> Hi @jimmidier @ravidhaduk
> 
> I Just research into this issue, I I find an existing Github Issues [5668](https://github.com/MicrosoftDocs/msteams-docs/issues/5668)
> 
> I checked the rate limit firstly and find out that it seems not go over the rate limit. Then I tried to click button several times, I found out that any request that last less than 15 seconds do not send me the duplicated result. Finally I dive into the action code, it seems like we don't manage a long-run operation as it is supposed to be.
> 
> Can we refer to ms doc: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0 and see if the problem still exist?
> 
> Thanks, Jack

Thanks for the investigation Jack. As I have just tested, the cards duplication issue is not appearing now, possibly as the result of sever upscaling we did earlier this year, but the "unable to reach app" issue is still occuring, which could still be related to lack of long operation handling, as per [this loop](https://github.com/MicrosoftDocs/msteams-docs/issues/6581) 

The MS doc you pasted is targeting Bot Framework SDK and it'll require extra effort to implement the same approach on Bot Composer. I've created #589 for this specific topic. 

Closing ths issue now.
