### ISSUE TITLE
✨New welcome message for Direct Line channel

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#502]
Cc: @jimmidier @pierssinclairssw @JernejK @drwharris @ravidhaduk 

Hi 
  
### Pain
Current welcome message has content specific to Teams channel. It is not appropriate for other products like SophieHub.
e.g. `Tip: Pin this chat, so you can always find me!`  

### Suggested Solution
We would like a separate more general default welcome message for Direct Line.

### Tasks

- [ ] Add a separate message for Direct Line - removing the tip from welcome message

### Screenshots

![image](https://user-images.githubusercontent.com/23565403/171118672-ac6a8dc1-cff7-47fb-a910-3c63114daa1f.png)
**Figure: Default welcome message has information specific to Teams**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done - Removed Tip from welcome message. <br/>
<img width="605" alt="Screen Shot 2022-06-01 at 1 54 24 pm" src="https://user-images.githubusercontent.com/80997507/171324855-cf861e5a-30cf-458d-9c16-fa77b2247c7b.png">
**Figure: Removed Tip from welcome message.**
