### ISSUE TITLE
✨Make welcome message configurable

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#503]
Cc: @jimmidier @pierssinclairssw @jernejk @drwharris @ravidhaduk

Hi 
  
### Pain

When a product is consuming SophieBot, they might want to use a customized welcome message.
e.g. SophieHub might want to change the welcome message to `This is SophieHub intergration with SophieBot`

### Suggested Solution

Allow the welcome message to be configured by products like SophieHub

### Tasks

- [ ] Make welcome message configurable

### Screenshots

![image](https://user-images.githubusercontent.com/23565403/171120256-f8cc166d-60f5-46fe-b910-cb1b100c2ff2.png)
**Figure: Default welcome message** 

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
