### ISSUE TITLE
✨Configure card actions to suit DirectLine and WebChat channel

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#506]
Cc: @jimmidier @pierssinclairssw @jernejk @drwharris @ravidhaduk

Hi 
  
### Pain

While using SophieBot through DirectLine channel or WebChat channel, the card actions (buttons) are configured specific to MSTeams.
This results in two consequences:
- Action buttons, when clicked, does not show as a user message in the chat box
- `imBack` type message is not recognized by the bot

### Tasks

- [x] Configure cards to be suitable for DirectLine channel
- [x] Configure cards to be suitable for WebChat channel

### Screenshots

![image](https://user-images.githubusercontent.com/23565403/171313291-5c6f77d6-33cb-4f6d-bbaa-4f7bd7a8710b.png)
**Figure: Message not recognized by SophieBot & missing user message box** 

![image](https://user-images.githubusercontent.com/23565403/171313464-251b450c-0da5-460e-94ec-7ce357193f77.png)
**Figure: Payload of the unrecognized message**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done - Configured card action for direct line and web chat. 

Putting the link of PR [here](https://github.com/SSWConsulting/SSW.SophieBot/pull/509) for refenence.

**Comment by ravidhaduk** [comment]
As per the conversation with Jim, I have configured only Welcome card's action for Direct LIne and Wenchat for now.
