### ISSUE TITLE
✨Change welcome message logo

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#508]
Cc: @jimmidier @pierssinclairssw @jernejk @drwharris @ravidhaduk @tiagov8 

Hi 
  
### Pain

The Logo for SophieBot welcome message is outdated.

### Suggested Solution

As per our conversation with @tiagov8, we are
1. updating the Logo in welcome message (refer to: https://www.ssw.com.au/ssw/logo/SophieBot/)
2. resizing the logo to 75% for DirectLine and Webchat channels only.

### Tasks

- [ ] Change the logo for MSTeams channel
- [ ] Change the logo for DirectLine channel and resize to 75%
- [ ] Change the logo for WebChat channel and resize to 75%

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done 
- Updated SophieBot logo on welcome card.
- Rezied image to 75% for Direct Line and other channels. 

![image](https://user-images.githubusercontent.com/80997507/171572527-bca3ad6f-9e54-4b1b-b25c-031a61ec8f79.png)
**Figure: Updated SophieBot Logo on Welcome card.**
