### ISSUE TITLE
🐛 Several commands are having "didn't understand" response

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#510]
Cc: @ravidhaduk @sylhuang

### To Reproduce
1. Go to MS Teams
2. Ask SophieBot "What's the email of Uly?"
3. See SophieBot responds "Sorry I didn't understand. Can you please try again?" (see screenshot below)

### Expected Behavior

SophieBot will responds with a proper text or card

### Tasks
- [x] Investigate
- [x] Fix

### More Information

See [this doc for Duplicated intents event](https://docs.microsoft.com/en-us/composer/how-to-define-triggers?tabs=v2x#duplicated-intents-recognized) for reference

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/172120013-5445e766-da2a-4bfa-bd86-0791aeffe1df.png)

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
- [x] Added Duplicated intents event handler to handle the "ChooseIntent" intent resulted from multiple recognizers (i.e. LUIS and QnA)
- [x] Added a job step on the workflows for both envs to build and publish the QnA model generated from cross-training
![image](https://user-images.githubusercontent.com/16027480/172835782-d911b969-3fcb-43a2-8d7d-17e115b117e8.png)
**Figure: The same question that caused the bug is now working as expected**

This bug is fixed now. Closing the issue.
