### ISSUE TITLE
✨Improve card styles for Direct Lines and Web Chat Channel

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#511]
Cc:

Hi @jimmidier @ravidhaduk @pierssinclairssw @tiagov8
  
### Pain

As per my conversation with @adamcogan, the styling of card returned by the bot could be improved more to fit SophieHub widget.

### Suggested Solution

Update the card styles for Direct Lines and Web Chat channels only.

### Tasks

~- [ ] Change action button from blue to black~
- [x] Increase font size of content text to be more readable
- [x] Report any style not modifiable through bot end

### Screenshots

![image](https://user-images.githubusercontent.com/23565403/172125141-ac2f23b9-dd30-4a40-8350-667217365f54.png)
**Figure: Button style to be changed**

![image](https://user-images.githubusercontent.com/23565403/172124479-1e0bad73-51e5-484a-8e1c-5518b340bb55.png)
**Figure: Text style to be changed**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Font sizes for content texts have now been changed from "Small" to "Default" (1 level larger)
![image](https://user-images.githubusercontent.com/16027480/173173872-635fadeb-99b5-48eb-a2ba-0d80d1db065d.png)
**Figure: Larger font size**

Closing the issue
