### ISSUE TITLE
✨ Connect Bot to SharePoint API

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#518]
Cc: @adamcogan @pierssinclairssw 

Hi @duanxinhuan @ravidhaduk 
  
### Pain

When query about SharePoint pages, the answers are hard coded

### Suggested Solution

Connect SophieBot to SharePoint using SharePoint API

### Tasks

- [x] Investigate
- [ ] Create tasks
- [ ] Implement

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Duplicate issue of ✨ Integrate Where do you want to go today #350. So, closing this.
