### ISSUE TITLE
✨ Send QR code

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#519]
Cc: @adamcogan @jimmidier 

Hi @duanxinhuan @ravidhaduk 
  
### Pain

SophieBot is not able to send its QR code in SSW Rreward

### Suggested Solution

Enabling SophieBot send QR code
### Tasks

- [x] Add SophieBot as a user in SSW Reward
- [x] Get SophieBot's QR Code
- [x] Add GetQRCode intention for SophieBot
- [x] Send QR code!

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [x] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
Done - Query added. 

Here's the SophieBot response when you ask "Show me your QR code"

![image](https://user-images.githubusercontent.com/80997507/175174899-a4eb605f-b4fa-47c0-b432-93aa35e0c18b.png)
**Figure: SophieBot response on "Show me your QR code"**
