### ISSUE TITLE
✨ Add nick name to SoopheBot

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#524]
Cc: @adamcogan @ravidhaduk @jimmidier 

Hi @duanxinhuan 
  
### Pain

SophieBot is unable to recognise nick name
### Suggested Solution

1. Add nick name 'JD' to SophieBOt
2. Making SophieBot 'learn' nick name interactively on UI
### Tasks

- [ ] Add nick name 'JD'
- [ ] Research and figure out a way to train SophieBot while using it

### Screenshots

![image](https://user-images.githubusercontent.com/48227836/174214809-34d791bb-79bb-41dd-b0ec-b0de3072172a.png)
Figure: AOphieBot is unable to recognise JD

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by duanxinhuan** [comment]
Jayden prefer others to call him Jayden, so no need to add his nick.
