### ISSUE TITLE
👷 DevOps | Integrate SharePoint Sync flows into pipeline

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#525]
Cc: @jimmidier 

Hi 
  
### Pain

We have two Power Automate flow to sync SharePoint page "Where do you want to go?" in the QnA maker. We created those manually. We need to integrate that in our Pipline.

### Tasks

- [ ] Integrate SharePoint Flows into pipline

### More Information

Ask Scrum Master to share that two flow with you. Here are the two flow's name:
1. SophieBot - Refresh QnA Maker When SharePoint Page Modified
2. SophieBot - Add QnA from SharePoint Page.

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
