### ISSUE TITLE
✨ How other user can setup SophieBot

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#526]
Cc: @jimmidier 

Hi 
  
### Pain

We need to create a docs how other customer can setup SophieBot with their orgnization.

### Tasks

- [ ] Complete the Power Apps solution for tenant registration
- [ ] Create a documentation.

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
