### ISSUE TITLE
📝 Docs - How to create a Power Automate Flow and connect it with QnA

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#527]
Cc: @jimmidier @adamcogan 

Hi 

### Pain

We have two Power Automate Flow to sync data from SharePoint page "Where do you want to go?" to QnA maker. We need to create a documentation on how to create a power automate flow and how we can connect them with QnA maker.

### Tasks

- [ ] Create a documentation.

### More Information

Here are the two flow that had been created. Please ask scrum master to share those two flows with you when you designing this documentation. 

      1. SophieBot - Refresh QnA Maker When SharePoint Page Modified
      2. SophieBot - Add QnA from SharePoint Page.

Ideally, we need only one flow to refresh the QnA, but in this case, we needed second flow to get data in HTML format bceause our SharePoint page is .NET webpage which is not supported by QnA Maker. So, in the QnA Url, we have set the link as a second flow trigger.

### Screenshots

![image](https://user-images.githubusercontent.com/80997507/174230744-9cc1be5b-5593-42ea-a758-5f1802962a82.png)
**Figure: Flow to refresh QnA when SharePoint Page gets modified**

![image](https://user-images.githubusercontent.com/80997507/174230874-4079da97-cec7-4b32-8a9d-26efaba36f0f.png)
**Figure: Flow to get HTML content from SharePoint page**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by duanxinhuan** [comment]
Hi Ravi,

I think we can split it into 2 parts,
The first part is how to intergrate existing web page with SophieBOt

The second is how to automatically update QnA maker using power automate and SharePoint

Do you Agree?

Thanks,
Jack
