### ISSUE TITLE
📝 Update SophieBot Try Out page

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#528]
Cc: @jimmidier @adamcogan 

Hi 

### Pain

This PBI can be done after this PBI https://github.com/SSWConsulting/SSW.SophieBot/issues/527 

As per my conversation with Adam, we need to update sophiebot try out page. We need to add screenshot of SharePoint page before the QnA'a screenshot which will indicate that we are getting data from this page. After SophieBot QnA's screenshot, add a link "How to set up QnA with SharePoint" docs link.

### Tasks

- [ ] Add SharePoint page screenshot
- [ ] Add a link to documnetation, how to set up QnA with SharePoint.

### Screenshots

![image](https://user-images.githubusercontent.com/80997507/174233045-daca13d9-434c-498f-b3ce-73004581b430.png)
**Figure: add SharePoint page screenshot and link to docs here**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
