### ISSUE TITLE
✨ External link icon

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.SophieBot#531]
Hi SophieBot Team,
  
### Pain
Some of the buttons that appear on messages from Sophie are actually links. This surprises users.

### Suggested Solution
Buttons that are links should have a icon e.g. https://fontawesome.com/v5/icons/external-link-alt

As per https://www.ssw.com.au/rules/do-you-make-external-links-clear

### Tasks
- [x] Add icon to link buttons

### Screenshots

![Figure: This button is not a link](https://user-images.githubusercontent.com/38869720/174726825-393eacf6-9296-4f81-a9b4-4492e2e05268.png)
**Figure: This button is not a link**

![Figure: This button is a link](https://user-images.githubusercontent.com/38869720/174726911-458ba30c-7e0d-40a0-90f4-73fa4a3a6dba.png)
**Figure: This button is a link (Looks the same)**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by ravidhaduk** [comment]
As per the investigation, technically it is not possible to add Icon after the text in Adaptive Cards, We can only add icon before the text.

**Comment by ravidhaduk** [comment]
As per the conversation with Jayden, it is better to icon be more meaningful. We are about to make some changes n buttons on Adaptiva cards.

1. In Profile card, change from "View" to "Show" if button click will return result in SophieBot itself and put the meaningful icons.
2. In View bookings card, change logo of "More booking info" to PowerBI logo as it is going to Power BI reports.

- [ ] Implement the changes.

**Comment by ravidhaduk** [comment]
Done - Changes as follows:
1. Update buttons names and Icon to be more configurable (Profile card)
2. Update button text of View Bookings card.

Here's are the shots.

![image](https://user-images.githubusercontent.com/80997507/175838949-b03a870b-fc38-43ff-81be-f9175b04954a.png)
**Figure: Updates Icons and names of buttons on Profile card**

![image](https://user-images.githubusercontent.com/80997507/175839006-a99f067c-5ad3-4d3e-9cd6-aa5eada2ad0e.png)
**Figure: Put PowerBI logo on View bookings card's button**

Closing this issue as there’s no task to action.
