### ISSUE TITLE
✨Sync QnA from Power App to LUIS

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#535]
Cc:

Hi 
  
### Pain

We currently do not have a easy and secure way to let users from other orgnisations to configure QnA from their Orginisations.

### Suggested Solution

1. Making users to input question and answer in Power App to train it.
2. Create a table in power app and allow user to insert QnA
### Tasks

- [ ] Investigate how to train LUIS QnA using LUIS API
- [ ] Connect to API from Power App
- [ ] Create a flow to automatically sync QnA from Power App table

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
According to the description this should be a much wider topic, where we provide an admin portal for clients to manage NLP models during runtime. If so, then ideally it should not be restricted to only targeting QnA, but any other recognizer services as well. Thus the description needs to be more generic, both on NLP service and app service supported (e.g. the portal should also support web app + LUIS management instead of Power Apps only)

Furthermore, if there is an NLP management portal packaged with SophieBot, it should come with a data persistence layer (i.e. database) to store related model data. This can be easily achieved after migrating to Bot Framework SDK (where we'll define LUIS/QnA models with programming language rather than .lu files)

Therefore, this could be of a very low priority, and will need much more discussion on requirement details. 

Labelling this as "more info required".
