### ISSUE TITLE
✨Configure  People and Skill from Power App

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#536]
Cc:

Hi 
  
### Pain

We need to let user from other orgnisations to add people and skills from Power App to SophieBot

### Tasks

- [ ] Creating tables in Power App
- [ ] Using Power Auto Flow to sync tables into the data base

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Managing NLP models at runtime should be a more generic topic here, meaning that we should not restrict devs and users to a single synchronizing service like Power Apps. 

LUIS synchronizing is a WIP feature, which provides a generic LUIS model data seeding infrastructure at lower level. For Microsoft tech stack users like SSW, we need to provide an out-of-box system to use services like Power Apps, but at the same time making sure to make it optional for other users targeting non-Microsoft tech stacks and products.

@duanxinhuan Please update the description to clarify the requirements of this topic:
1. Replace the term "configure" with "Synchronize" as it should be focusing on an automated synchronizing flow rather than a management portal as discussed at #535 
2. Clarify that we need to build 2 parts of the system
   a. Complete the generic infrastructure of recognizer synchronizing
   b. Build a Power Apps synchronizing solution for LUIS
