### ISSUE TITLE
✨Different LUIS for different Orgnisation or one LUIS for all Orgnisations

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#537]
Cc:

Hi 
  
### Pain

We are currently having only one LUIS model on the cloud. However, if other orgnisation use LUIS, single LUIS may not be sufficient because the same question might have different meaning in different context.

### Tasks

- [ ] Investigate if we need multiple LUIS for different clients

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
This should not be an issue in real situation. Every tenant is meant to have a dedicated LUIS server to host their own LUIS service. Thus management and maintenance are completely separated between different tenants. The only shared artifact is the LUIS model developed by SophieBot team, which acts as a starting point for development and deployment, but does not cause any shared resource.
Closing this now.
