### ISSUE TITLE
✨Investigate into possibility of RASA

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#538]
Cc:

Hi 
  
### Pain

LUIS is owesome for SophoeBot because it is easy to use. However, if we want to sell SophieBot and get it used by hundreds of orginisations, then we will be in trouble manage hundreds of LUIS and Azure Bots.
However, RASA is an open source NLU library that allow us to have more control over develoment, deploy and testing.

### Suggested Solution

1. Replace LUIS with RASA

### Tasks

- [ ] Investigate if we can use RASA NLU with Bot Composer

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Thanks for rasing the suggestion Jack.
This is applicable as per https://rasa.com/docs/rasa/nlu-only, since Bot Framework is technically NLP agnostic.
However there are other things to factor during investigation
- Model capability
- List entity support (the dev flow of SophieBot includes feeding business data to model entities)
- DevOps integration

On the other hand, LUIS is on its way to retirement so we should also take Azure CLU into consideration.
