### ISSUE TITLE
✨Automate the configuration flow

### ISSUE THREAD

**Issue by duanxinhuan** [SSWConsulting/SSW.SophieBot#539]
Cc:

Hi 
  
### Pain

We currently do not have a flow to automate the registration of an orgnisation

### Suggested Solution

We can create a Power App to allow admins add Orgnisations.
Here is the flow Chart for Power App
```mermaid
flowchart TD;
    A[Admin fill in a from and create an orgnisation]-->B[A flow is triggered];
    B-->C[Call People Api to create an orgnisation]-->D[Create tables for the orgnisation in Power App]-->E[Share Power App to the user];
   
```

### Tasks

- [ ] If people API do not have add Orgnisation endpoint, add it in People APU
- [ ] Create the flow that can automatically share power App to the user
- [ ] Create UI in Power App

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
