### ISSUE TITLE
✨ Handle personalized requests

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.SophieBot#540]
Hi Team,
  
### Pain
I want to know what client I am working for tomorrow so I asked Sophie _"Who am I working for tomorrow?"_
She did not recognise that I wanted my booking details. 
I had to ask _"Who is Brady working for tomorrow"_

### Suggested Solution
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/38869720/176121729-54030c48-b1d2-4f97-a89c-a839b3519321.png">

**Figure: These queries should have the same result**

### Tasks
- [ ] When I use I/my, Sophie should recognise I want to know my information

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
