### ISSUE TITLE
✨Add a loading card - then edit it once the message is ready

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.SophieBot#541]
Cc:

Hi Team,
  
### Pain

Waiting for a response, for example 'Who is working on Northwind today' takes a long time: 10-20 seconds with no response.

### Suggested Solution

I would like a card with a loading message, loading spinner, etc., would be great. When the final message is ready - edit the loading message - or delete it, and send the two cards (not sure on the MS Teams limitations - I am used to Discord bots with a similar pattern)

### Tasks

- [ ] ...
- [ ] ...

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
