### ISSUE TITLE
✨ Bot - SysAdmins - Add new Queries

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#542]
Cc: 

Hi Team
  
### Pain

It's tough for account managers to find people with particular Job positions. It would be fantastic to have the following queries supported:
  1. Who is working for SSW and is a SysAdmin?
  2. Who are the SysAdmins?
  3. Who are Software developers?
  4. Who are Senior Software Architects? 

### Tasks

- [ ] Action the task.

### More Information

We already have queries supported with "AND" word such as
1. Who is free in Sydney office and have Angular skill?

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
