### ISSUE TITLE
♻️Exclude ex-employees in list results

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#544]
Cc: @PatrickZhao1989 @adamcogan 

### Pain
Ex-employees that are still being enabled on CRM are showing on the list results (e.g. results from Who is on internal work?). These should be excluded to align with the employees visible on Power BI reports.

### What code could be improved?
Change the code in People API to accept an extra parameter to filter out ex-employees.

### Tasks

- [ ] Add a parameter on People API | Employees query endpoint to support filtering by current employees/ex-employees
- [ ] Update SophieBot to use this parameter on all list results

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
