### ISSUE TITLE
✨SophieBot - It should tell people to create an issue when there is a bug

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.SophieBot#545]
Cc: @jimmidier @ravidhaduk 

Hi Ravi
  
### Pain
When there is a bug, SophieBot says to email the SophieBotDevs. Instead it should say create a GitHub issue in the repo and email a link to that PBI to the SophieBotDevs

### Suggested Solution
Message says to create an issue and email the link to SophieBotDevs

### Tasks

- [ ] Update the message

### Screenshots
![Figure: SophieBot doesn't say to raise a GitHub issue when there is a bug](https://user-images.githubusercontent.com/79821522/189272550-53fc279b-8f70-4f1d-8959-9d82f7bd18d6.png)

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by AshAnil** [comment]
Hi Team,

I was trying to check “who is in the Sydney office today?” and got an error. Kindly find the screenshot 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/100336252/189274775-4d3e7025-9470-48db-9cd7-58195baacd08.png)

1. Please investigate

**Comment by ravidhaduk** [comment]
Done - Update error message to tell user to create a GitHub issue.
![image](https://user-images.githubusercontent.com/80997507/194478607-0e97c0cf-c050-469e-bf86-318053889f3e.png)
**Figure: Updated error message**
