### ISSUE TITLE
✨I'd like to know when someone starts working

### ISSUE THREAD

**Issue by billyterblanche** [SSWConsulting/SSW.SophieBot#547]
Cc:

Hi 
  
### Pain
When SophieBot returns a users card, it will be nice if we can see when that person will be available. This will assist the people working remotely in different time zones.

### Suggested Solution
We could include the person's working hours information in the user card, next to Last Seen. Maybe indicate time until next available?

### Tasks

- [ ] ...
- [ ] ...

### Screenshots
![image](https://user-images.githubusercontent.com/10550900/190187971-85b07d24-8feb-4ed3-a77b-36a09c0160fc.png)

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
