### ISSUE TITLE
✨ New Query - What are Jonty's WFH days?

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#548]
Cc:

Hi Team
  
### Pain

SophieBot couldn't answer what day employees work from home and in the office. 

Please add a PBI for Sophie bot to be able to answer the following questions:
          a.	what are Jonty's working hours?
          b.	what are Jonty's WFH days?
          c.	What are Jonty's work from home days?

The answer to any of these should be to expose the “Work Hours” field in CRM | Users | Details:

![image](https://user-images.githubusercontent.com/80997507/190289339-2e534a7b-74ee-45cd-95a6-9effba620622.png)
Figure: [User: User: Jonty Gardner - Dynamics 365](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.crm6.dynamics.com%2Fmain.aspx%3Fappid%3D05daa2a9-8768-446e-b9d3-580c8a6f9b8b%26pagetype%3Dentityrecord%26etn%3Dsystemuser%26id%3Dc6f63945-aa5b-ec11-8f8f-00224814efc4&data=05%7C01%7CRaviDhaduk%40ssw.com.au%7Ccc025f580e174ff67ab008da96b425af%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C637987997725077730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FBByvUFiUypo07oM0WRPSdOZouNvuB6niSBXkG8QY7w%3D&reserved=0)

![image](https://user-images.githubusercontent.com/80997507/190289402-94823e81-bbd5-4599-bff0-7e7a06aa60e8.png)
Figure: Sophie cannot answer these questions yet
### Tasks

- [ ] Action the task

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by AttackOnMorty** [comment]
Will show `Work Hours` on the profile card. See #621
