### ISSUE TITLE
✨ Query - Support query locations by business unit

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#554]
Cc: @JeanThirion @adamcogan 

Hi Team,
  
### Pain

Currently, our location query is based on the Site filed in CRM. Our current organizational structure is like below:
- SSW
  - Sydney
  - Melbourne
  - Brisbane
  - Newcastle
- SSW China
  - China
- SSW France
  - Europe

We can not do the query based on the business unit. Like, who is in Europe?

### Tasks

- [x] Check the email (Re: SophieBot - Feedback) from @JeanThirion to see the final organizational structure
- [x] Support the query

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Done - This is fixed from People API. Email replied in the same loop with subject RE: SophieBot - Feedback.
Closing the issue
