### ISSUE TITLE
✨ New fields on Calendar card

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#561]
Cc: @adamcogan @ravidhaduk 

To Myself
  
### Pain

It would be nice for managers to see start date as well as end date of a calendar record.

### Suggested Solution

1. Make sure PeopleAPI store the two fields
2. Update calendar card to render both fields

### Tasks

- [x] Make sure PeopleAPI store the two fields
- [x] Update calendar card to render both fields

### Screenshots

![image](https://user-images.githubusercontent.com/16027480/219248741-e973c894-a89a-4aa8-a2b8-1ace3642bf30.png)
**Figure: Current calendar card only shows a "Date" column**

![image](https://user-images.githubusercontent.com/16027480/219248760-1b9c49bc-4efd-441d-9c56-6407a51aba45.png)
**Figure: Start and end date info in data source**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
