### ISSUE TITLE
🐛 Appointment without Regarding is causing incorrect return date

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#562]
Cc: @adamcogan @ravidhaduk 

To Myself

### Describe the Bug

![image](https://user-images.githubusercontent.com/16027480/219336276-2b4a8b54-7ce5-440d-8c8d-f864c14fa054.png)
**Figure: One of the employee is said to be back on 31st Jan but it was actually 30th Jan**

### Expected Behavior

The back date on profile card is correct

### Tasks
- [x] Investigate
- [x] Fix

### More Information

This was due to the appointments on 30th Jan not having Regarding field and thus be skipped while calculating the return date.

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
I've pushed through a fix #586 to address this issue. Closing now.
