### ISSUE TITLE
✨Who is in Melbourne now - Extend inoffice tolerance minutes and make it settable

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#564]
Cc: @adamcogan @ravidhaduk 

Hi Team,
  
### Pain

When asking for employees currently in office (e.g. "Who is in Melbourne now"), managers easily lost track of employees if they leave the office for several minutes. Suggesting to extend the time range query and keep tracking employees that have left the office for a longer time.

### Suggested Solution

Keep tracking employees for 7 hours.

### Tasks

- [ ] Update _inOfficeToleranceMinutes static variable in PeopleAPI to be a query param
- [ ] Use the new query param to extend inoffice tolerance time range

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
