### ISSUE TITLE
🐛 Error 500 on People API

### ISSUE THREAD

**Issue by ravidhaduk** [SSWConsulting/SSW.SophieBot#565]
Cc: @jimmidier @william-liebenberg 

Hi Team

### Describe the Bug

On 03 March 2023, SophieBot was down for around 1 hour. The reason was People API throwing 500 Error. We looked at the AppInsights and noticed some 401 errors with UniFi Sync, which was causing timeout issues and the people API doesn’t seem to handle that very well. We need to fix that.  

We restarted SophieBot App Service and Azure function in the backend to see if it solves the issue and it solved the issue. We need to investigate more about what was happening. 

We have attached excel files that hold logs for requests and exceptions from that period of time in case it gets deleted when someone starts working on this.
[Exceptions.csv](https://github.com/SSWConsulting/SSW.SophieBot/files/10876917/Exceptions.csv)
[Requests.csv](https://github.com/SSWConsulting/SSW.SophieBot/files/10876918/Requests.csv)

### Tasks
- [x] Investigate

### Screenshots

Here's the reference from AppInsights

![image](https://user-images.githubusercontent.com/80997507/222588603-4cd3b6c9-579d-4be0-bf1f-debd4f9c8937.png)
**Figure: See red boxes, its 500 Error on People API request** Source: [App Insights](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22b8b18dcf-d83b-47e2-9886-00c2e983629e%22%2C%22ResourceGroup%22%3A%22SSW.SophieBot%22%2C%22Name%22%3A%22SSWSophieBot%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fb8b18dcf-d83b-47e2-9886-00c2e983629e%252FresourceGroups%252FSSW.SophieBot%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252FSSWSophieBot%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22bc7f2f11-ba95-4186-9bb8-797c217ff4aa%22%2C%22timestamp%22%3A%222023-03-02T22%3A24%3A10.229Z%22%2C%22cacheId%22%3A%22dd8f340f-c416-4e3f-ba87-d7ff20ef9e83%22%2C%22eventTable%22%3A%22dependencies%22%7D)

More info about UniFi error. 

![image](https://user-images.githubusercontent.com/80997507/222599386-c37d510e-5ce0-49c4-a5f0-4c1ff0f284f8.png)
![image](https://user-images.githubusercontent.com/80997507/222599441-ae8a466e-7a9d-41cc-83ae-586126968703.png)
Figure: Source: [AppInsights](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22b8b18dcf-d83b-47e2-9886-00c2e983629e%22%2C%22ResourceGroup%22%3A%22SSW.Bots%22%2C%22Name%22%3A%22ssw-people%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fb8b18dcf-d83b-47e2-9886-00c2e983629e%252FresourceGroups%252FSSW.Bots%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fssw-people%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22baf9dcdc-b951-11ed-b3ec-4132afbd45c3%22%2C%22timestamp%22%3A%222023-03-02T23%3A26%3A35.562Z%22%2C%22cacheId%22%3A%22c025237a-c3bb-4c5c-bef4-e5119b1a4e56%22%2C%22eventTable%22%3A%22dependencies%22%7D)

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
- The 401 error PeopleAPI encountered was not fatal as the error is properly captured in a try-catch block.
- The 500 error SophieBot encountered was very likely to be an UniFi login issue back at the time when the controller server was being adjusted by the administrator. As per the logs for the past month such error is not occurring
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/35948a6a-73b5-455d-9aaf-03d62074a3e6)
**Figure: Logs show only 3 irrelevant 500 errors (not due to PeopleAPI failure) for the past month**
- That said, I've improved the logic in PeopleAPI to prevent it from querying Unifi controller if the site name is empty (which is the cause of the 500 error)
