### ISSUE TITLE
📝 Update doc - Run with Bot Framework Composer

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#575]
Cc: @adamcogan @duanxinhuan @jimmidier 

To myself,

### Pain

I followed [Run bot with Bot Framework Composer](https://github.com/SSWConsulting/SSW.SophieBot/blob/main/_docs/Instructions-Compile.md) but I can't get the bot up and running. There are 2 problems here:
1. I am stuck on step `2. Set up App ID. Still in the Configure | Development resources, scroll to the bottom.` There is nothing for me to select. This is because we are missing the `publishTargets` field in the `appsettings.json` and the doc doesn't tell us how to fill this field.
2. The doc also doesn't show us how to fill the `HttpClient` and `App` fields in the `appsettings.json`, which are needed for the bot to run.

### Suggested Documentation

- We should store the `appsettings.json` in the SophieBot Teams channel and reference it in the doc. 

The reason is that we automatically generate the first `publishTargets` when we provision the Azure resources. Although we can fill `publishTargets` by checking every resource that the bot uses, it's time-consuming and developer-unfriendly.

### Tasks

- [ ] Add `appsettings.json` to the SophieBot Teams channel
- [ ] Update the doc

### Screenshots

<img width="1440" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/ba4e18f0-dd8f-481d-a4c6-c908c3a081bf">

**Figure: Nothing to select after clicking Retrieve App ID**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
