### ISSUE TITLE
✨ Implement long operation prompt

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#589]
Cc: @duanxinhuan 

  
### Pain

This feature is to implement long operation prompt as mentioned in #500 

### Tasks

- [ ] Investigate feasibility
- [ ] Implement feature

### More Information

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
