### ISSUE TITLE
♻️ Unifi | Improve interaction to reflect more real-time user state

### ISSUE THREAD

**Issue by jimmidier** [SSWConsulting/SSW.SophieBot#594]
Cc: @AttackOnMorty 

### Pain

Current "in office" data only shows last seen time even it's just a few minutes ago which doesn't reflect people who are still in the office at the moment.

### What code could be improved?

When the command is sent, SophieBot needs a way to request Unifi directly to fetch the current logged in users to get more precise results.

### Tasks

- [ ] Add endpoint in PeopleAPI
- [ ] In SophieBot, use the new endpoint in dialog flow

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by AttackOnMorty** [comment]
It's fixed in #600
