### ISSUE TITLE
🐛 SophieBot encountered a bug with Teams question

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#598]
Cc: @jimmidier 

Hi @AttackOnMorty 

### Describe the Bug

SophieBot encountered a bug while asked an unknown question on Teams.

### To Reproduce
1. Go to SophieBot on Teams
2. Ask the question: "how many initial meetings has Piers done"
3. See SophieBot replied with: "The SophieBot encountered an error or bug. Please create a Github issue in the [repo](https://github.com/SSWConsulting/SSW.SophieBot) and send us an email with link to that GitHub issue to SSWSophieBotDevs@ssw.com.au"

### Expected Behavior

It should not say the bot encountered a bug. If the answer is unknown, the bot should just say she does not know.

### Tasks
- [x] Investigate
- [x] Fix

### Environment
 - Device: Dell laptop
 - OS: Windows 10

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/23565403/c597ceb9-94b3-4247-801f-b8fa94c37619)
**Figure: Asking SophieBot on Teams**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Done - Fixed the null pointer exception and the incorrect recognition
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/f8c05e63-5ac2-404c-b377-8418f96504fb)
**Figure: The same command now gets an "unknown" response**
