### ISSUE TITLE
🐛 Who works in Brisbane office

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#601]
Cc: @jimmidier @william-liebenberg @adamcogan 

To myself,

### Describe the Bug

When asking "Who works in Brisbane office right now", it shows there are 2 people in the office. But it shows more than 2 people after I do a follow-up query "Who is in Brisbane office right now"

### Tasks
- [x] Investigate
- [x] Fix

### Screenshots

<img width="690" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/a0afdcc4-81d2-45a7-8e5d-fb3d2031dea1">

**Figure: It should only show Bryden and Brady are in the office**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by AttackOnMorty** [comment]
We need add `fromDate` and `endDate` params back in https://github.com/SSWConsulting/SSW.SophieBot/pull/604/files.  Because we have queries like "Who was in Brisbane office last Friday"
