### ISSUE TITLE
✨ Enhance profile card

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#603]
Cc: @jimmidier @william-liebenberg @adamcogan 

To myself,

### Tasks

- [ ] Add device name at the end of the last seen
- [ ] Add an external icon for `SSW People` and `CRM`

### Screenshots

<img width="1004" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/94f9a5a2-5eb0-4a48-a177-cc6a24901e83">
<img width="1013" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/112187b6-6942-44b0-bdcc-7f2c41ffb1ab">

**Figure: No device info**

<img width="992" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/0afcc502-4ecd-4dfd-b45b-c46409a51de0">

**Figure: No external icon**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Tooltip on text field is not yet supported on Adaptive Card v1.5 ([The latest version supported in MS Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards)), but [tooltip on action button has just been supported](https://adaptivecards.io/blog/2021/Announcing-1.5/) in this version.
Alternatives:
- Display in brackets directly after the last seen info
- Use hide/show arrow like the one in Skills section to optionally display under the last seen info

**Comment by AttackOnMorty** [comment]
As per conversation with @adamcogan, we will add the device name at the end of the last seen. Like below:

<img width="1003" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/905c57a0-9ff9-48a9-b54c-ce2e78eb7e40">

**Figure: Mockup**

**Comment by AttackOnMorty** [comment]
> Add device name at the end of the last seen

It also needs changes in PeopleAPI: [Devices not syncing correctly from CRM](https://dev.azure.com/ssw/SSW.SophieBot/_sprints/backlog/SSW.SophieBot%20Team/SSW.SophieBot/PeopleBot%20-%20Sprint%203?workitem=84162)

**Comment by AttackOnMorty** [comment]
> Add an external icon for `SSW People` and `CRM`

No way to add extra icon in the end. Adaptive Cards doesn't support it.

**Comment by AttackOnMorty** [comment]
Done - see below

<img width="1008" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/63582bea-c76e-4e92-b6b1-c2b81adcd532">

**Figure: Add device name to last seen field**
