### ISSUE TITLE
🐛 Use proper pronouns in answer

### ISSUE THREAD

**Issue by sylhuang** [SSWConsulting/SSW.SophieBot#605]
Cc: @jimmidier 

Hi @AttackOnMorty 
  
### Pain

SophieBot only uses 'He' in its answer, which is not always the right pronoun. For people unfamiliar with the queried staff, it could results in misleading information. 

![1692926398272](https://github.com/SSWConsulting/SSW.SophieBot/assets/23565403/c4824f01-e527-48f0-b71a-40888a902720)
**Figure: SophieBot refers to Sylvia as 'He'**

### Suggested Solution

Give SophieBot more context to use the appropriate pronouns.

### Tasks

- [ ] ...
- [ ] ...

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
Done - The static "He" in the response is now replaced with the person's first name as CRM doesn't contain gender information
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/e08082f9-f1e0-4e1e-a7a2-b031037d4ba8)
