### ISSUE TITLE
♻️ Simplify profile buttons

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#608]
Cc: @adamcogan @pierssinclairssw @GordonBeeming @jimmidier 

To myself,

### Pain

The titles for the profile buttons can be more concise.

### What code could be improved?

 - Change "Show Projects" to "Projects"
 - Change "Show Bookings" to "Bookings"
 - Change "View in People" to "SSW People"
 - Change "View in CRM" to "CRM"

### Tasks

- [ ] Investigate
- [ ] Implement

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/9efc82c8-1235-432d-aa74-5e1644602b17)
**Figrue: Current buttons in profile card**

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
