### ISSUE TITLE
✨ Add more logs to the Application Insights

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#609]
Cc: @adamcogan @pierssinclairssw @GordonBeeming @jimmidier 

To myself,
  
### Pain

The query "Who is in Brisbane office now" was not working before and we don't know when that happened. We need to add more logs to the Application Insights.

### Suggested Solution

Add Application Insights to:
- SophieBot to record the query result
- People API to record the UniFi calls

### Tasks

- [x] Investigate
- [x] implement

### Definition of Done
- [ ] All tasks are updated and closed
- [ ] No high priority defects/bugs are on that user story
- [ ] Code reviewed by one other team member (e.g. Checked by Bill)
- [ ] All acceptance criteria have been met
- [ ] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [ ] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [ ] Complex code is documented (removing technical debt)
- [ ] Deployed to Production
- [ ] Add description about the changes for the PBI
- [ ] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by jimmidier** [comment]
> People API to record the UniFi calls  

Telemetry in People API UniFi calls is already implemented
![1693996563727](https://github.com/SSWConsulting/SSW.SophieBot/assets/16027480/77c347c4-50ac-4a3f-b81a-8bc009f77181)
**Figure: Existing logs in [Azure App Insights](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.Bots/providers/microsoft.insights/components/ssw-people/logs)**
