### ISSUE TITLE
✨ Who is in office now

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#610]
Cc: @adamcogan @pierssinclairssw @GordonBeeming @jimmidier 

To myself,
  
### Pain

We don't support the queries to ask all the employees in the office now.
- Who is in SSW now?
- Who is in office now?

### Suggested Solution

We should show a card with the message "There are xx people in the office right now" and the following options:
- Show All
- Sydney
- Melbourne
- Brisbane
- Newcastle

### Tasks

- [x] Investigate
- [ ] Implement

### Screenshots

<img width="1000" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/584f85d3-e201-4c5b-8f0d-fa7753c5d3f6">

**Figure: No result when asking all offices**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [ ] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by AttackOnMorty** [comment]
Closed by https://github.com/SSWConsulting/SSW.SophieBot/pull/613

**Comment by AttackOnMorty** [comment]
TODO:

- [ ] Support query - who is in SSW now
- [ ] Add location selection card instead of showing all

**Comment by AttackOnMorty** [comment]
Done

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/ffc70f25-b1be-4df5-b170-87db636de90f)

**Figure: Query - who is in office now**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/73550bf2-f8dc-48db-9fd6-063e7f5d4342)

**Figure: Query - who is in SSW office now**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/b9a40a95-0f51-4b94-8d7b-626ae7f18980)

**Figure: Query - who is in SSW now**
