### ISSUE TITLE
🐛  Missing time info for query - Who is in Brisbane office now

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#615]
Cc: @jimmidier @BrookJeynes @william-liebenberg @adamcogan 

To myself

### Describe the Bug

There is no time info if you ask "Who works in Bisabne?" then click "(6 in the office right now)".
But if you ask "Who is in Brisbane office right now" directly, you can see the time info.

### Tasks
- [ ] Investigate
- [ ] Fix

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/544201cc-0df4-4864-b768-4d983ee496e7)

**Figure: Ask "Who works in Bisabne?" first**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/445d30ba-a807-4afe-ae70-64f988bf8d0c)

**Figure: Ask "Who is in Brisbane office right now"**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!
