### ISSUE TITLE
🐛 Data is correct for query - Who's been using SophieBot

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#618]
Cc: @jimmidier @BrookJeynes @william-liebenberg @adamcogan 

To myself

### Describe the Bug

See screenshots.

### Tasks
- [ ] Investigate
- [ ] Fix

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/5ae6a307-6c30-45b9-8647-c062303e8ad2)

**Figrue: Data from SophieBot**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/5eea709c-794f-49ec-a85e-621bf071f08d)

**Figure: Actual data**

### Definition of Done
- [x] All tasks are updated and closed
- [x] No high priority defects/bugs are on that user story
- [x] Code reviewed by one other team member (e.g. Checked by Bill)
- [x] All acceptance criteria have been met
- [x] Deployed to Dev
- [x] (If implemented) Pass automated UI testing
- [x] (If not implemented above) Do a manual test on all supported commands (at least one for each LUIS intent) against Dev
- [x] Complex code is documented (removing technical debt)
- [x] Deployed to Production
- [x] Add description about the changes for the PBI
- [x] Tick off the definition of done tasks in the PBI
- [ ] (Optional) A Done Video, particularly for PBI with multiple stages

Thanks!

**Comment by BrookJeynes** [comment]
All fixed - 
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/25432120/2308c48f-e1d6-4360-83d3-05e6d4616236)
