### ISSUE TITLE
✨ Add work hours to profile card

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#621]
Cc: @jimmidier @BrookJeynes @william-liebenberg @adamcogan 

To myself
  
### Pain

> Hi Luke
I always forget which days Kiki is working… it is Tue, Thu and Fri.
If it is not normal it would be good to see in SophieBot.
> 1. Under “Last Seen” could you add the field in CRM that has his working days (but only if it is not null)

### Tasks

- [x] Investigate
- [x] Add `workHours` field to employees endpoint
- [x] Display Work Hours on profile card

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/edb83649-1164-4e51-9b3f-0e06bd4bdc75)
**Figure: Current profile**

### Acceptance Criteria

- [x] Meets [Definition of Done](https://github.com/SSWConsulting/SSW.SophieBot/blob/main/_docs/Definition-of-Done.md)
- [x] `Work Hours` is consistent with CRM

Thanks!

**Comment by AttackOnMorty** [comment]
Done

<img width="1001" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/a3476288-3d1d-4078-a42d-5fbff5ae12df">

Figure: `Work Hours` added

**Comment by adamcogan** [comment]
Hi @jimmidier 
This is inconsistent with CRM.

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/1222712/e4bc024c-7596-4841-ace1-ae231627d259)

Vs

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/1222712/20efa287-8be8-4fca-a8fc-0fd4a32309f6)

1. Please investigate and fix

-a

**Comment by AttackOnMorty** [comment]
> 1. In code, how did the line breaks get lost?

- The Adaptive Cards doesn't interpret the line breaks correctly 
- I used `|` to replace the line breaks to make the content more compact.

> 2. Please investigate and fix

Done

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/b14ac80e-b034-4c2c-8b1b-ecfcc7f899e1)

**Figure: `Work Hours` now is consistent with CRM**

**Comment by jimmidier** [comment]
Hi @adamcogan 
  > This is inconsistent with CRM. Did you check the UI?  

I was not aware of the requirement that the text format should be consistent with the one in CRM, so I approved the PR after checking the code change and attached screenshot.
  > If not, what process in your PR approval should change?  

As per above, it's an issue of misunderstanding of the acceptance criteria so I think it's the issue description that need be improved rather than the PR approval process.

**Comment by AttackOnMorty** [comment]
> 1. In code, how did the line breaks get lost?

- The Adaptive Cards doesn't interpret the line breaks correctly 
- I used `|` to replace the line breaks to make the content more compact.

> 2. Please investigate and fix

Done

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/ee3e67b1-3f92-4209-9c41-520a40832171)


**Figure: `Work Hours` now is consistent with CRM**
