### ISSUE TITLE
🐛 Project data is not correct

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#634]
Cc: @jimmidier @adamcogan 

To myself,

### Describe the Bug

When asking the query - "Show Luke Mao's project", the data is not correct because I worked on WiseTech within the last 90 days.

### Tasks
- [x] Investigate
- [x] Fix

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

### Screenshots

<img width="1052" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/bbd681f0-4e92-4c81-923a-350d65b8abcb">

**Figure: Luke Mao's projects** 

Thanks!

**Comment by AttackOnMorty** [comment]
The data is incorrect because SophieBot is calling the old endpoint. See https://dev.azure.com/ssw2/SSW.TimeProDotNet/_workitems/edit/52656/

**Comment by AttackOnMorty** [comment]
To fix this issue, we need to finish the following WIs (No changes needed on SophieBot)
- [ ] TimePro - [✨ Add missing fields to /ProjectBreakdownReport/RowsV2](https://dev.azure.com/ssw2/SSW.TimeProDotNet/_workitems/edit/52656/)
- [ ] SSW.People.API - [Migrate to new ProjectBreakdownReport endpoint](https://dev.azure.com/ssw/SSW.SophieBot/_workitems/edit/85174)

**Comment by AttackOnMorty** [comment]
Done

<img width="984" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/685411f4-d7c5-4690-b1be-c0b5932c8299">

**Figure: Get correct project data based on the timesheet data of the previous 90 days**
