### ISSUE TITLE
✨ Support query - Who is the {{ ROLE }} for the SSW Website

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#639]
Cc: @jimmidier @bradystroud @pierssinclairssw @adamcogan 

To myself,
  
### Pain

As a user, I want to know the following role of a certain project.
- Scrum Master
- Tech Lead
- Product Owner
- Product Owner (secondary)

### Tasks

- [ ] Investigate
- [ ] Implement

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] Support query - Who is the **Scrum Master** of SSW Webiste
- [ ] Support query - Who is the **Tech Lead** of SSW Webiste
- [ ] Support query - Who is the **Product Owner** of SSW Webiste

### Screenshots

<img width="1020" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/f96bab2b-b638-4aa9-b81a-9929788b3b11">

**Figure: Inaccurate answer**

Thanks!
