### ISSUE TITLE
🐛 Fix query "Who is on SSW Website"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#640]
Cc: @jimmidier @bradystroud @pierssinclairssw @adamcogan 

To myself,

### Describe the Bug

For query "Who is on SSW Website", it should show me the project card instead of the people card.
For query "Who is working on SSW Website", it's working fine.

### Tasks
- [x] Investigate
- [x] Fix

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [x] Show project card for query "Who is on SSW Website"
- [x] Show project card for query "Who is on website project"
- [x] Show project card for query "Who is working on website project"

### Screenshots

<img width="1040" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/2e639053-c7ab-4493-af32-c68f9b061943">

**Figure: SophieBot got wrong intent for "who is on {{ Project }}"**

Thanks!

**Comment by AttackOnMorty** [comment]
Done - Fixed the following queries:
-  "Who is on SSW Website"
- "Who is on website project"
- "Who is working on website project"

<img width="714" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/94d2a87a-8727-4ab2-9cc8-08ac0b3073b3">

**Figure: Got correct response for project-related queries**
