### ISSUE TITLE
✨GPTify SophieBot

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.SophieBot#643]
Cc: @adamcogan @jimmidier 

Hi @AttackOnMorty 
  
### Pain

SophieBot should respond more naturally to user queries.

For example, if I ask "Who are the Angular masters in Victoria?" it should be able to figure out that this is the same as "Who has Angular skills in Melbourne?"

It should be able to do this for any variation of the question.

### Suggested Solution
Either Power Virtual Agents or Semantic Kernel

### Tasks

- [ ] Investigate how to use GPT to translate questions into existing intents
- [ ] Investigate if Power Virtual Agents can do this
- [ ] Investigate if Power Virtual Agents or Semantic Kernel is a better choice
- [ ] Implement the solution

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] SophieBot figures out what intent my question should be.

Thanks!
