### ISSUE TITLE
✨ Move SSW.People.API to GitHub

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#644]
Cc: @pierssinclairssw @adamcogan @jimmidier 

To myself,
  
### Pain

We have 2 backlogs cos we have [SSW.People.API](https://dev.azure.com/ssw/SSW.SophieBot) on Azure DevOps, which is hard to maintain.

### Tasks

- [ ] Walk through the doc and backlog of the SSW.People.API
- [ ] Move SSW.People.API to GitHub

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

Thanks!
