### ISSUE TITLE
🐛 Appointment data is not correct

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#645]
Cc: @JackDevAU @jimmidier  @pierssinclairssw @adamcogan 

To myself,

### Describe the Bug

For the query "who is on client work?", the data is not correct.
It returned 4 people but there are more than 4 people on client work based on CRM.

### Tasks
- [x] Investigate
- [x] Fix

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [x] Get correct for "who is on Client work?"
- [x] Get correct for "who is on Client work in {{ Location }}?"

### Screenshots

<img width="993" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/da87a81e-4e15-4807-8914-82410956d61d">

**Figure: 4 people on client work in SophieBot**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/153365d2-9d6a-4f3d-99eb-a88d6d6fbf89)

**Figure: More than 4 people on client work in CRM**

Thanks!

**Comment by AttackOnMorty** [comment]
> - [x] Get correct for "who is on Client work?"

Done - Fixed in https://dev.azure.com/ssw/SSW.SophieBot/_git/SSW.People.API/commit/557957c0c7700ebe0d6fd3a97249ba26b4036c14

> - [x] Get correct for "who is on Client work in {{ Location }}?"

Done - Fix in https://github.com/SSWConsulting/SSW.SophieBot/pull/647

<img width="1013" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/210e67f9-c7b8-4ca9-960d-f21fcd0c7640">

**Comment by AttackOnMorty** [comment]
#647 reverted. Still need to fix:
- [ ]  Get correct for "who is on Client work in {{ Location }}?"
