### ISSUE TITLE
♻️ Rename intents and dialogs

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#648]
Cc: @jimmidier @pierssinclairssw @adamcogan 

To myself,

### Pain

The names of intents and dialogs are inconsistent. For example: we have intents called `GetEmployeesByProject` and `GetPeopleBySkills`. `GetEmployeesByProject` should be renamed to `GetPeopleByProject`.

Keeping good and consistent names is also beneficial for moving to other technology.

### Tasks

- [ ] Rename `GetPeopleBasedOnLocation` to `GetPeopleByLocation`
- [ ] Rename `GetEmployeesByProject` to `GetPeopleByProject`
- [ ] Rename `GetCurrentEmployeesOnLocation` to `GetPeopleInOffice`
- [ ] Rename `GetEmployeeProjects` to `GetProjects`
- [ ] Rename `CheckAvailability` to `GetAvailability`

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

### Screenshots

<img width="366" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/68188f5b-e301-4b1a-9088-61f87cfaf6d8">

**Figure: Existing intents**

Thanks!
