### ISSUE TITLE
♻️ SSW.People.API - Migrate to .NET 8

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#652]
cc: @jimmidier @jackreimers @GordonBeeming @pierssinclairssw @adamcogan

SSW.People.API currently uses:
- .NET 6
- .NET Standard 2

```[tasklist]
### Tasks
- [x] Migrate to .NET 8 as per https://www.ssw.com.au/rules/rules-to-better-net8-migrations/
- [x] Switch Azure Functions model from `In-process` to `Isolated worker process`
- [x] Fix unit tests
- [x] Test locally
- [x] Test after deploying to prod
```

ACs
- [x] Users can get correct answers for all the queries on https://sswsophie.com/sophiebot/try/

**Comment by AttackOnMorty** [comment]
To use .NET 8, we have to switch the Azure Functions model from `In-process` to `Isolated worker process`, which is a big change. 

See https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#supported-versions

**Comment by AttackOnMorty** [comment]
PR: https://dev.azure.com/ssw/SSW.SophieBot/_git/SSW.People.API/pullrequest/4831
