### ISSUE TITLE
✨ Support "who is in office now" for China

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#654]
Cc: @babakamyljanovssw @jimmidier @pierssinclairssw @adamcogan 

To myself,
  
### Pain

- For the query "who is in {{ Location  }} office now?", SophieBot can't get online user data in China office.

### Tasks

- [ ] Investigate
  - [ ] How does current UniFi work across the Australia offices?
  - [ ] Can we add the Hangzhou office as a site to the current endpoint?
- [ ] Implement (Call China UniFi endpoint to get the data if we can't add it to the current UniFi endpoint)
- [ ] Fix - Show "I couldn't find anyone in China office at this time." when no one is in office.

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

### Screenshots

<img width="1009" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/f90412f0-6702-4d17-8420-40e0fd776046">

**Figure: No one is in China office in working hours**

Thanks!
