### ISSUE TITLE
✨  Tell me about the {{ Client Name }}

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#655]
Cc: @jimmidier @pierssinclairssw @adamcogan 

To myself,
  
### Pain

SophieBot doesn't support directly asking for client info, e.g. "Tell me about the {{ Client Name }}"

### Tasks

- [ ] Add necessary client fields in PeopleAPI
- [ ] Support query in SophieBot

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/aa9cb4e7-4805-441e-85f2-08813f67f130)
**Figure: Query not supported**

Thanks!
