### ISSUE TITLE
🐛 Fix query "Who works in the Sydney office?"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#657]
Cc: @jimmidier @pierssinclairssw @UlyssesMaclaren @adamcogan 

To myself

### Describe the Bug

Feedback from Betty,
> Typing in “Who works in the Sydney office?” returns “Please specify a valid date to query.”
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/40db319e-5a07-4fcf-96e6-f5447f56bc17)
> Clicking on any of the buttons to narrow your search returns “Sorry I didn’t understand. Can you please try again?
![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/416df071-bc3d-424e-9da1-c0ef8d891700)

### Tasks
- [x] Investigate
- [ ] Fix

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [x] Show skill card for query "Please specify a valid date to query."
- [x] Show people list after clicking the skill button

Thanks!

**Comment by AttackOnMorty** [comment]
Find another problem related to this query
- [ ] Investigate and fix

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/3f97feec-97ff-42e3-9cd1-1892a178e82e)
**It shows 15 people but the title shows 12 after clicking the `.NET` button**

**Comment by AttackOnMorty** [comment]
✅ Done

<img width="1005" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/05aaf731-6625-4457-85cb-f5a2ab3312fa">

**Figure: Asking “who works in the Sydney office”**

<img width="1032" alt="image" src="https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/f491eb53-6864-45da-a7aa-8f5eae4d6c38">

**Figure: Click “Show All”**

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/9fb22911-7c4b-4e63-b18e-3a2e227c519d)
**Figure: Click the skill button (The number of people is correct now)**
