### ISSUE TITLE
🐛 Welcome image is broken

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#662]
Based on email chain:

From: @YalalCakirSSW
Date: Thursday, 14 December 2023 at 11:04
To: SSWSophieBotDevs <SSWSophieBotDevs@ssw.com.au>
Cc: @adamcogan, @Marxoz, @christoment
Subject: SSW SophieBot - Broken Welcome Image 

Hi team,

### Describe the Bug

> I found this bug when I’m using the SophieBot. When I send my first message, I got a “Welcome” message from SophieBot but I got received broken image.
For more reference, please check the figure below.

### Tasks
- [x] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] Show the SophieBot icon when sending the first message
- [ ] Reply 'Done' to the email and also @mention them in the PBI with 'Done'

### Screenshots

![image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/9fac27a9-7044-488d-942a-74d2944419b7)
**Figure: Broken Welcome Image**

Thanks!

**Comment by AttackOnMorty** [comment]
> Investigate

Can't reproduce this issue. Moved it to low priority.

- Tested in local. It works fine.
- Checked logs on App Insights. No failed request when accessing welcome image.


![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/d58316e0-fecd-40b3-9400-144cb516ad55)
**Figure: Test in local**

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/7ae84c74-c221-4ecf-824c-45c17783d1fd)
**Figure: No image error in the last 3 months**
