### ISSUE TITLE
✨ Support query - Who takes the AI-102 exam?

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#665]
Based on email chain:

From: @drwharris
Date: Wednesday, 28 February 2024 at 23:12
To: @AttackOnMorty 
Cc: @adamcogan @jimmidier 
Subject: Do we store which Exam people have passed

### Pain

The user wants to know who takes a specific Azure exam - "Who takes the AI-102 exam?"

### Tasks

- [ ] Sync the User Benefits data into the SophieBot
- [ ] Support the query "Who takes the AI-102 exam?"

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] Show people cards when asking who takes a specific Azure exam

Thanks!
