### ISSUE TITLE
✨ Investigate common metrics for SSW products

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#688]
Cc: @jimmidier @divgul @matt-goldman @piers-sinclair @adamcogan @william-liebenberg

Hi Team
  
### Pain

We need to figure out common metrics for all SSW products.

```[tasklist]
### Tasks
- [x] Investigate
- [x] Check by PO @william-liebenberg
- [x] Create PBI to implement
```

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

Thanks!

**Comment by AttackOnMorty** [comment]
We can get the following common metrics (with data sources in parentheses) from App Insights.

For usage
- Page views (**pageViews**)
- Users (**pageViews**)

For errors:
- Exceptions (**exceptions**)
- Failed requests (**requests**)

For performance
- Request execution time (**requests**)
- Available memory (**performanceCounters | Available Bytes**)
- CPU (**performanceCounters | % Processor Time Normalized**)

**Comment by AttackOnMorty** [comment]
> Create PBI to implement

✅ Done - See #692
