### ISSUE TITLE
✨ Data export for prod App Insights

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#689]
Cc: @jimmidier @divgul @matt-goldman @piers-sinclair @adamcogan @william-liebenberg

Hi Team,
  
### Pain

We need to set up the data export for prod App Insights.

> **Classic Application Insights was retired on February 29, 2024**
> Microsoft will begin an automatic phased approach to migrating classic resources to workspace-based resources beginning in May 2024. We don't have estimated dates for when specific resources, subscriptions, or regions will migrate. Contact a resource owner to migrate now.

[SophieBotDev](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot.Dev/providers/microsoft.insights/components/SSWSophieBotDev/overview) is already workspace-based. But [SophieBot](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot/providers/Microsoft.Insights/components/SSWSophieBot/overview) (Prod) is not.

```[tasklist]
### Tasks
- [x] Migrate SophieBot prod App Insights to Workspace-based
- [x] Set up data export for prod
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

Thanks!

**Comment by AttackOnMorty** [comment]
✅ Done - Prod App Insights are now continues exported to the [am-appevents](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot/providers/Microsoft.Storage/storageAccounts/sswsophiebot/storagebrowser). Refer to https://github.com/SSWConsulting/SSW.SophieBot/issues/690#issuecomment-2081885232 for field details.
