### ISSUE TITLE
✨ POC - Export data from Log Analytics to Azure Blob Storage

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#690]
Cc: @jimmidier @divgul @matt-goldman @piers-sinclair @adamcogan @william-liebenberg 

Prerequisite:
- #668 
  
### Pain

Investigate how easy to Export data from Log Analytics to Azure Blob Storage. If it's easy, we will directly build Power BI reports from Azure Blob Storage (We were planing to build reports from App Insights)

### Tasks
```[tasklist]
### Tasks
- [x] Request access to Log Analytic workspace
- [x] Implement
- [x] Investigate what fields are queried in Workbooks reports
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] Can see the custom matrix in Azure Blob Storage
- [ ] Know what fields to query in Power BI reports

### More Information

Doc: [https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Flogs%2Flogs-data-export%3Ftabs%3Dportal&data=05%7C02%7CLukeMao%40ssw.com.au%7C25e0365567574e116d0a08dc57980b20%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638481557748164378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tPE0TB9WNdfv46slZZiq%2F53H7HUhdQj0dMP9v9JzryE%3D&reserved=0)

Thanks!

**Comment by AttackOnMorty** [comment]
✅ Done - Exported Dev App Insights to the Azure Blob Storage. Data is stored in [am-appevents](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot.Dev/providers/Microsoft.Storage/storageAccounts/sswsophiebotdev/storagebrowser).

Also did some investigation on current Workbooks reports. This can give us some reference on which fields to query for building Power BI reports.
- [Usage by Query](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot/providers/microsoft.insights/workbooks/9fb19046-749e-42d5-ab97-9e8ce136d026/workbook)
- [Usage by User](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot/providers/microsoft.insights/workbooks/fd17f38d-4cb2-4fe8-9c94-32b430375504/workbook)

The data source comes from `customEvents` with name equals `LuisResult`. 

The detailed fields are listed below (The fields in brackets are corresponding fields in Blob Storage):

- timestamp (TimeGenerated)
- name (Name)
- customDimensions.intent (Properties.intent)
- user_AccountId (UserAccountId)

**Comment by AttackOnMorty** [comment]
Note: [SSWSophieBotDev](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot.Dev/providers/microsoft.insights/components/SSWSophieBotDev/overview) App Insights is moved to [log-sswsophiebot](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.SophieBot/providers/Microsoft.OperationalInsights/workspaces/log-sswsophiebot) workspace.
