### ISSUE TITLE
✨ Add URL for explanation when device has no name in CRM

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#691]
Based on email chain:

From: @adamcogan 
Date: Sunday, 5 May 2024 at 20:00
To: @AttackOnMorty 
Cc: @kikibianc @camillars
Subject: SophieBot - “last seen” is inconsistent about showing “Device”
  
### Pain

SophieBot is showing the "Device" name when asking "Who is kiki". But when asking "who is Camilla", it doesn't show "Device".

It's confusing to the user and makes them wonder what's the logic behind this.

### Tasks

- [x] Show "Device: Unknown" when the employee doesn't fill in the device name in CRM
- [x] Add a hyperlink to the "Unknown" and link it to the WiKi to explain this.

### Acceptance Criteria

- [x] Meets [Definition of Done](../../_docs//Definition-of-Done.md)

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/13634298-5a67-4e97-a327-af729798fced)
**Figure: "Device" name is inconsistent**

Thanks!

**Comment by AttackOnMorty** [comment]
✅ Done

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/0f988cb5-de83-42bd-92ef-a450cd8dd5f6)
**Figure: Show "Unknown" when the device name is empty and link to the [doc](https://github.com/SSWConsulting/SSW.SophieBot/wiki/Frequently-Asked-Questions#1-why-my-device-name-in-the-profile-card-is-unknown)**
