### ISSUE TITLE
✨ Export common metrics from App Insights to Blob Storage

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#692]
Cc: @divgul @william-liebenberg @jimmidier @adamcogan @matt-goldman 

Depends on
- #689 
  
### Pain

We did the investigation on what common metrics to track in #688.

We need to export these fields in https://github.com/SSWConsulting/SSW.SophieBot/issues/688#issuecomment-2084509439 to Azure Blob Storage.

### Suggested Solution

```[tasklist]
### Tasks
- [x] Export data
- [x] Document the corresponding fields in Blob Storage
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [x] Data is exported to Blob Storage
- [ ] Have a note on the fields in Blob Storage

Thanks!

**Comment by AttackOnMorty** [comment]
Below are the important fields in App Insights tables (with corresponding Blob Storage fields in brackets).

### pageViews

Data about each website view with browser information.

- timestamp (TimeGenerated)
- name (Name)
- url (SophieBot DOESN'T have this field)
- user_AccountId (UserAccountId)

**Note: For SophieBot, we can skip the report for this table. Because SophieBot is not a web application. It doesn't have `url` field.**

### exceptions

Exceptions thrown by the application runtime, captures both server side and client-side (browsers) exceptions.

- timestamp (TimeGenerated)
- problemId (ProblemId)
- type (Type)

### requests

Requests received by your application. For example, a separate request record is logged for each HTTP request that your web app receives.

- timestamp (TimeGenerated)
- name (Name)
- url (Url)
- success (Success)
- responseCode (ResultCode)
- duration (DurationMs)

### dependencies

Calls from the application to other components (including external components) recorded via TrackDependency() - for example, calls to REST API, database or a file system.

- Fields are same as in requests table.

### performanceCounters

Performance measurements from the compute resources supporting the application, for example, Windows performance counters.

- timestamp (TimeGenerated)
- name (Name)
- value (Value)
