### ISSUE TITLE
🎥 Upload Sprint 32 video to YouTube channel

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#696]
Cc: @william-liebenberg @adamcogan 

Video Title
```
Sprint 32 - SSW.SophieBot - Review & Planning Meeting 2024-05-08
```

Video Description:
```
Join us for Sprint 32 - SSW.SophieBot - Review & Planning Meeting

{{ TIMESTAMP_SUMMARY_FROM_AI }}

🔗  Links:
https://sswsophie.com/sophiebot
```

Video Thumbnail Template:
https://sswcom-my.sharepoint.com/:p:/g/personal/lukemao_ssw_com_au/EaxtsjNw20NPmh3hJ98sQUQB_L2nyFnhwjhk4hhnqVw7Tg

### Acceptance Criteria
1. Public can see this week's video on YouTube channel

```[tasklist]
### Tasks
- [x] Upload this week's Sprint video with Title and Description to YouTube channel
- [x] Generate thumbnail from the template and add it to the video
- [x] Add the video to the Playlist
``` 

### Information
- YouTube Channel: https://www.youtube.com/channel/UCHZ1tNIIldeIZChB8DTqBKw
- Playlist: https://www.youtube.com/playlist?list=PLnkcTBhDzoQ2IZkSJwqDYj4CXAIaeAuxh

**Comment by AttackOnMorty** [comment]
✅ Done - Video uploaded: https://www.youtube.com/watch?v=rato6WOLjy0
