### ISSUE TITLE
✨ SophieBot - Add redirect text for query - "Who is in {{ OFFICE }} now"

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#708]
Based on email chain:

From: Luke Mao [SSW] <LukeMao@ssw.com.au>
Date: Wednesday, 10 July 2024 at 17:20
To: @AttackOnMorty 
Cc: @adamcogan, @joshbermanssw
Subject: SophieBot - Add redirect text for query - "Who is in {{ OFFICE }} now"

  
### Pain

When asking "who is in {{ OFFICE }} now?", we only show people whose phone is connected to the Kiwi.
But we might also want to know who was in the office today.

### Suggested Solution

Add “See people in office today” at the top. It will redirect to the query “who is in {{ OFFICE }} today?”

```[tasklist]
### Tasks
- [ ] Implement
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] User can click the text "See people in office today" to see who is in office today.
- [ ] Reply 'Done' to all emails mentioned in this PBI and @mention the sender with 'Done'

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/37203901/4d076e91-ed71-4c32-a9f0-72fa14bcfd5e)
**Figure: Add text to the red box**

Thanks!
