### ISSUE TITLE
✨ Automate testing of query - who is in office now

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.SophieBot#725]
Cc: @adamcogan @jimmidier 

Hi Team
  
### Pain

Every Wednesday, I need you to manually test the query (who is in office now) for each office.
- Test query on SophieBot for each office
- Check with people in each office to see who is missing
- Send a reminder email to each person

### Suggested Solution

Automate the process based on the Daily Scrum email.
- Check if the email body contains "Location: WFH"
- Call People API to check if that person is in the office
- Send the reminder if they are not in office

**NOTE:** we need an exclusion list because Luke C is allowed not connected to Kiwi because of some security reason

```[tasklist]
### Tasks
- [ ] Investigate
- [ ] Implement
- [ ] Update Daily Scrum template
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] Reminder email is sent when people are WFO but didn't connect to the Kiwi

Thanks!
